$axure.loadCurrentPage({
  "url":"首页动态条.html",
  "generationDate":new Date(1481889394611.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ce4694f6bafa4b17912fe9dc89fbc713",
    "type":"Axure:Page",
    "name":"首页动态条",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8caf2451ccc54d6e8b9d599d706d81c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":54,
              "y":324},
            "size":{
              "width":279,
              "height":68},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be74241e1424df58ff5df66113c6d07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":54,
                  "y":324},
                "size":{
                  "width":279,
                  "height":68},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动态条/u0.png"}},
{
          "id":"4396efa33e814956babe5b919ffe4223",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":173,
              "y":337},
            "size":{
              "width":149,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de9859debf1c44d8a0d03616f009c7cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":337},
                "size":{
                  "width":149,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"199990b2295c4ca0899c696c688a9fe1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":331},
            "size":{
              "width":10,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/中间页交互/u68_line.png"}},
{
          "id":"3b32dc8a113e4f2e974d5d7565e0522e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":173,
              "y":359},
            "size":{
              "width":149,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5a700b2b7374e5884b705a1b922cc5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":359},
                "size":{
                  "width":149,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"769e9ab0bf0c493182a97d1de5637c02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":324},
            "size":{
              "width":183,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe15f05a165e4f59b70612c5b488b1a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":343,
                  "y":324},
                "size":{
                  "width":183,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"276beda77e264b1f800a9ab0ba454ae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":618,
              "y":324},
            "size":{
              "width":172,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3819d4ebaef491e9c5a73f1b682c7d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":618,
                  "y":324},
                "size":{
                  "width":172,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bea449b0785a44ba93a2abb4d9f4f504",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":363},
            "size":{
              "width":259,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3707efb66d8f4c1d978f706f7883778e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":343,
                  "y":363},
                "size":{
                  "width":259,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7714799355244388995eddb715527a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":436},
            "size":{
              "width":213,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c5c4e5b6434656b1552b7859a4d77d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":343,
                  "y":436},
                "size":{
                  "width":213,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8badd1cc029476b8da62f7f9177ab57",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Negreta', 'Agency FB'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":76,
              "y":336},
            "size":{
              "width":49,
              "height":45},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6ec5e0ef1bc4efabf7e9f70447d3f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Negreta', 'Agency FB'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":76,
                  "y":336},
                "size":{
                  "width":49,
                  "height":45},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u30.png"}},
{
          "id":"8a0558fa87564710a8cb307cce7e6727",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":54,
              "y":40},
            "size":{
              "width":263,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef727c77a9fd49af9dff7b1ded9dfacc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":40},
                "size":{
                  "width":263,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d94af976ac914f6fb90877732f9605ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":54,
              "y":96},
            "size":{
              "width":279,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03131fcd5f89486e9b1f4682589e704b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":54,
                  "y":96},
                "size":{
                  "width":279,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u26.png"}},
{
          "id":"c49f5c6126634ba39500ec194c5e6ed3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":163,
              "y":106},
            "size":{
              "width":159,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4b6d5c7093e47c0b338f37d077823e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":163,
                  "y":106},
                "size":{
                  "width":159,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8af87fa26bfb40fcaf222a48aa9e1137",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Negreta', 'Agency FB'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":76,
              "y":102},
            "size":{
              "width":49,
              "height":45},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a665cc083ee34838adc6e5f05af8e631",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Negreta', 'Agency FB'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":76,
                  "y":102},
                "size":{
                  "width":49,
                  "height":45},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u30.png"}},
{
          "id":"e32093802d814a7993b0a7d0f9074b96",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":102},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录流程/u32_line.png"}},
{
          "id":"bd988207e54c436682682e8c26adc291",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":112},
            "size":{
              "width":248,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"395b6a3805764ae8bd906a97fdd9119c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":112},
                "size":{
                  "width":248,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a115a21401d24b2aa6c4325ec80f204f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":206},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b54e39fcea49c69e7483d61422b104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":206},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a71063f79ab74231a886443ff0ba358c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":186},
            "size":{
              "width":360,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20064fa2d13f46918cf803541de77aeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":186},
                "size":{
                  "width":360,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2915c4945a54f8d8644f097e4572fe2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":56,
              "y":295},
            "size":{
              "width":275,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1de952a146749e5a6fc47fc819a760f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":295},
                "size":{
                  "width":275,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8caf2451ccc54d6e8b9d599d706d81c2":{
      "scriptId":"u0"},
    "0be74241e1424df58ff5df66113c6d07":{
      "scriptId":"u1"},
    "4396efa33e814956babe5b919ffe4223":{
      "scriptId":"u2"},
    "de9859debf1c44d8a0d03616f009c7cc":{
      "scriptId":"u3"},
    "199990b2295c4ca0899c696c688a9fe1":{
      "scriptId":"u4"},
    "3b32dc8a113e4f2e974d5d7565e0522e":{
      "scriptId":"u5"},
    "f5a700b2b7374e5884b705a1b922cc5e":{
      "scriptId":"u6"},
    "769e9ab0bf0c493182a97d1de5637c02":{
      "scriptId":"u7"},
    "fe15f05a165e4f59b70612c5b488b1a4":{
      "scriptId":"u8"},
    "276beda77e264b1f800a9ab0ba454ae9":{
      "scriptId":"u9"},
    "f3819d4ebaef491e9c5a73f1b682c7d0":{
      "scriptId":"u10"},
    "bea449b0785a44ba93a2abb4d9f4f504":{
      "scriptId":"u11"},
    "3707efb66d8f4c1d978f706f7883778e":{
      "scriptId":"u12"},
    "b7714799355244388995eddb715527a7":{
      "scriptId":"u13"},
    "d1c5c4e5b6434656b1552b7859a4d77d":{
      "scriptId":"u14"},
    "a8badd1cc029476b8da62f7f9177ab57":{
      "scriptId":"u15"},
    "e6ec5e0ef1bc4efabf7e9f70447d3f9d":{
      "scriptId":"u16"},
    "8a0558fa87564710a8cb307cce7e6727":{
      "scriptId":"u17"},
    "ef727c77a9fd49af9dff7b1ded9dfacc":{
      "scriptId":"u18"},
    "d94af976ac914f6fb90877732f9605ac":{
      "scriptId":"u19"},
    "03131fcd5f89486e9b1f4682589e704b":{
      "scriptId":"u20"},
    "c49f5c6126634ba39500ec194c5e6ed3":{
      "scriptId":"u21"},
    "a4b6d5c7093e47c0b338f37d077823e9":{
      "scriptId":"u22"},
    "8af87fa26bfb40fcaf222a48aa9e1137":{
      "scriptId":"u23"},
    "a665cc083ee34838adc6e5f05af8e631":{
      "scriptId":"u24"},
    "e32093802d814a7993b0a7d0f9074b96":{
      "scriptId":"u25"},
    "bd988207e54c436682682e8c26adc291":{
      "scriptId":"u26"},
    "395b6a3805764ae8bd906a97fdd9119c":{
      "scriptId":"u27"},
    "a115a21401d24b2aa6c4325ec80f204f":{
      "scriptId":"u28"},
    "d5b54e39fcea49c69e7483d61422b104":{
      "scriptId":"u29"},
    "a71063f79ab74231a886443ff0ba358c":{
      "scriptId":"u30"},
    "20064fa2d13f46918cf803541de77aeb":{
      "scriptId":"u31"},
    "f2915c4945a54f8d8644f097e4572fe2":{
      "scriptId":"u32"},
    "d1de952a146749e5a6fc47fc819a760f":{
      "scriptId":"u33"}}});