$axure.loadCurrentPage({
  "url":"弹窗消息提醒.html",
  "generationDate":new Date(1480575723644.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3a7f81eeab5a4c1ea064e103fd070642",
    "type":"Axure:Page",
    "name":"弹窗消息提醒",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"effb69dd848c4bf6920cff5240517a6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":32},
            "size":{
              "width":193,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33076c1c809e4bf08917042f6b537adf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":32},
                "size":{
                  "width":193,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb6478848615484ba15ed9822bad5daf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":60,
              "y":90},
            "size":{
              "width":172,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcdf69b10310462c99df4caa385c2d39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":60,
                  "y":90},
                "size":{
                  "width":172,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a17189fd05a7455896c6078e70474b53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":219},
            "size":{
              "width":272,
              "height":481}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42047ef971414a8d87e09b089986c86b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":219},
                "size":{
                  "width":272,
                  "height":481}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动画提醒/u46.jpg"}},
{
          "id":"268c1f8b27c74470a88fe89d984c76a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":219},
            "size":{
              "width":80,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d68e24fa24f49a69571145c0af684f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":219},
                "size":{
                  "width":80,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动画提醒/u48.png"}},
{
          "id":"91a6092303fc4ae9b19963cd07daffdc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":219},
            "size":{
              "width":271,
              "height":481}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46226e0b835f41fd8a398b9137db372a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":219},
                "size":{
                  "width":271,
                  "height":481}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u20.jpg"}},
{
          "id":"946aba44b35f4936a0debee3fc23a965",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":252},
            "size":{
              "width":266,
              "height":206}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24bd15b9f21e4bc09130a9cd4bd1c50b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":374,
                  "y":252},
                "size":{
                  "width":266,
                  "height":206}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u22.png"}},
{
          "id":"705c364d5f324872b63d3b4625613c6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":570},
            "size":{
              "width":149,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9a264bcf8264c37903fd0808e0a8605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":570},
                "size":{
                  "width":149,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u24.png"}},
{
          "id":"98943247078143ac809bc06d0668ff4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":460,
              "y":581},
            "size":{
              "width":93,
              "height":93},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b919788a1674e2fa7d254d895314eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":460,
                  "y":581},
                "size":{
                  "width":93,
                  "height":93},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动画提醒/u56.png"}},
{
          "id":"e23745cfdcdb40a698fb6e6ce549b068",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":381,
              "y":273},
            "size":{
              "width":249,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46770d497d544c418b43dbc061187d55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":381,
                  "y":273},
                "size":{
                  "width":249,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1dd1b00c0c14fccb64362fcb69195c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":219},
            "size":{
              "width":271,
              "height":481}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37510b5bf2a74d86bf38e3358c3c2417",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":219},
                "size":{
                  "width":271,
                  "height":481}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动画提醒/u64.jpg"}},
{
          "id":"c26b13b355424d878ac614bc31b2ea2a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":630},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd5faabc003e4dd0ba88d42dd2926f58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":630},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}]},
{
          "id":"9f17cbce440e4ae1878dd2af50629276",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":698,
              "y":252},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"245942ea86d94eff8938abf0d9af49cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698,
                  "y":252},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1dcab83e7074f66b46d754a9556ca32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":280,
              "y":90},
            "size":{
              "width":400,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b69b2571afad4782875a31035242b35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":280,
                  "y":90},
                "size":{
                  "width":400,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca28c28b62fa4106b3ab4e360a2a4ab6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":460},
            "size":{
              "width":230,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dff563fab2c47bcadff59149676324b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":460},
                "size":{
                  "width":230,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗消息提醒/u26.png"}},
{
          "id":"a606f6e262be4848af165f6d0d5bcb12",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":103,
              "y":533},
            "size":{
              "width":197,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccdb9208dafa4343bc803f2066600d50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":103,
                  "y":533},
                "size":{
                  "width":197,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"969b79fecb72494f8440814df8c5484b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":279,
              "y":483},
            "size":{
              "width":28,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"005b1f8e2721412a8d4a1c7af00596b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":279,
                  "y":483},
                "size":{
                  "width":28,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32be9c13c6a0404b8956e7b72f1124c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":163,
              "y":484},
            "size":{
              "width":69,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f2a2cbf5e22473b8cef80a9508ffedf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":484},
                "size":{
                  "width":69,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99979b2446cb4d509b77f4430792efc1",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":590},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da2698e62f6c4437a48948ef28b43f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":590},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}]},
{
          "id":"8e4a22430e3041cc908b85c37788143f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":381,
              "y":298},
            "size":{
              "width":249,
              "height":232},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7856966d536e4edfb6431b445b47a40b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":381,
                  "y":298},
                "size":{
                  "width":249,
                  "height":232},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗消息提醒/u36.png"}},
{
          "id":"682460a548c2494a8d78291a22c30b10",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":392,
              "y":314},
            "size":{
              "width":203,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8be855f5642e4f73b6267d7680ab3462",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":392,
                  "y":314},
                "size":{
                  "width":203,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d394566a4bb9404d986185da6f4e9509",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":354},
            "size":{
              "width":73,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa6793b9d07c427aa605f6f63fa18dc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391,
                  "y":354},
                "size":{
                  "width":73,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗消息提醒/u40.png"}},
{
          "id":"2d12fd99aaa444e1b50d418c0e1c0837",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":469,
              "y":354},
            "size":{
              "width":73,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35f9e76e264342a5914443b4b39218dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":469,
                  "y":354},
                "size":{
                  "width":73,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗消息提醒/u40.png"}},
{
          "id":"c8abe652b09840b8b8ee72f406d2f829",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":548,
              "y":354},
            "size":{
              "width":73,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd231efdd43e4d05a44322438e11d914",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":548,
                  "y":354},
                "size":{
                  "width":73,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗消息提醒/u40.png"}},
{
          "id":"be62cd8490d44a19a473009d51a97fe7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":435},
            "size":{
              "width":73,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"644f4289230b4e57805b4a9f2b24556e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391,
                  "y":435},
                "size":{
                  "width":73,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗消息提醒/u40.png"}},
{
          "id":"cac3c94d80884f8791865a5dfc5af097",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":468,
              "y":435},
            "size":{
              "width":73,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8620cc853613481db7613931aeae348b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":468,
                  "y":435},
                "size":{
                  "width":73,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗消息提醒/u40.png"}},
{
          "id":"17e0417e42f9400d9332619dee87df58",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":548,
              "y":435},
            "size":{
              "width":73,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd995b983c814ec1b0a3ffa17426fe15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":548,
                  "y":435},
                "size":{
                  "width":73,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗消息提醒/u40.png"}},
{
          "id":"c7b36dab0dd2447dac3ea8a5c5bd123d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":508},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83f08a9c8978497096de8c8613d34723",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":508},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "effb69dd848c4bf6920cff5240517a6b":{
      "scriptId":"u0"},
    "33076c1c809e4bf08917042f6b537adf":{
      "scriptId":"u1"},
    "bb6478848615484ba15ed9822bad5daf":{
      "scriptId":"u2"},
    "fcdf69b10310462c99df4caa385c2d39":{
      "scriptId":"u3"},
    "a17189fd05a7455896c6078e70474b53":{
      "scriptId":"u4"},
    "42047ef971414a8d87e09b089986c86b":{
      "scriptId":"u5"},
    "268c1f8b27c74470a88fe89d984c76a6":{
      "scriptId":"u6"},
    "2d68e24fa24f49a69571145c0af684f9":{
      "scriptId":"u7"},
    "91a6092303fc4ae9b19963cd07daffdc":{
      "scriptId":"u8"},
    "46226e0b835f41fd8a398b9137db372a":{
      "scriptId":"u9"},
    "946aba44b35f4936a0debee3fc23a965":{
      "scriptId":"u10"},
    "24bd15b9f21e4bc09130a9cd4bd1c50b":{
      "scriptId":"u11"},
    "705c364d5f324872b63d3b4625613c6a":{
      "scriptId":"u12"},
    "d9a264bcf8264c37903fd0808e0a8605":{
      "scriptId":"u13"},
    "98943247078143ac809bc06d0668ff4f":{
      "scriptId":"u14"},
    "0b919788a1674e2fa7d254d895314eff":{
      "scriptId":"u15"},
    "e23745cfdcdb40a698fb6e6ce549b068":{
      "scriptId":"u16"},
    "46770d497d544c418b43dbc061187d55":{
      "scriptId":"u17"},
    "c1dd1b00c0c14fccb64362fcb69195c5":{
      "scriptId":"u18"},
    "37510b5bf2a74d86bf38e3358c3c2417":{
      "scriptId":"u19"},
    "c26b13b355424d878ac614bc31b2ea2a":{
      "scriptId":"u20"},
    "cd5faabc003e4dd0ba88d42dd2926f58":{
      "scriptId":"u21"},
    "9f17cbce440e4ae1878dd2af50629276":{
      "scriptId":"u22"},
    "245942ea86d94eff8938abf0d9af49cb":{
      "scriptId":"u23"},
    "c1dcab83e7074f66b46d754a9556ca32":{
      "scriptId":"u24"},
    "b69b2571afad4782875a31035242b35f":{
      "scriptId":"u25"},
    "ca28c28b62fa4106b3ab4e360a2a4ab6":{
      "scriptId":"u26"},
    "4dff563fab2c47bcadff59149676324b":{
      "scriptId":"u27"},
    "a606f6e262be4848af165f6d0d5bcb12":{
      "scriptId":"u28"},
    "ccdb9208dafa4343bc803f2066600d50":{
      "scriptId":"u29"},
    "969b79fecb72494f8440814df8c5484b":{
      "scriptId":"u30"},
    "005b1f8e2721412a8d4a1c7af00596b7":{
      "scriptId":"u31"},
    "32be9c13c6a0404b8956e7b72f1124c4":{
      "scriptId":"u32"},
    "0f2a2cbf5e22473b8cef80a9508ffedf":{
      "scriptId":"u33"},
    "99979b2446cb4d509b77f4430792efc1":{
      "scriptId":"u34"},
    "da2698e62f6c4437a48948ef28b43f3d":{
      "scriptId":"u35"},
    "8e4a22430e3041cc908b85c37788143f":{
      "scriptId":"u36"},
    "7856966d536e4edfb6431b445b47a40b":{
      "scriptId":"u37"},
    "682460a548c2494a8d78291a22c30b10":{
      "scriptId":"u38"},
    "8be855f5642e4f73b6267d7680ab3462":{
      "scriptId":"u39"},
    "d394566a4bb9404d986185da6f4e9509":{
      "scriptId":"u40"},
    "fa6793b9d07c427aa605f6f63fa18dc3":{
      "scriptId":"u41"},
    "2d12fd99aaa444e1b50d418c0e1c0837":{
      "scriptId":"u42"},
    "35f9e76e264342a5914443b4b39218dd":{
      "scriptId":"u43"},
    "c8abe652b09840b8b8ee72f406d2f829":{
      "scriptId":"u44"},
    "fd231efdd43e4d05a44322438e11d914":{
      "scriptId":"u45"},
    "be62cd8490d44a19a473009d51a97fe7":{
      "scriptId":"u46"},
    "644f4289230b4e57805b4a9f2b24556e":{
      "scriptId":"u47"},
    "cac3c94d80884f8791865a5dfc5af097":{
      "scriptId":"u48"},
    "8620cc853613481db7613931aeae348b":{
      "scriptId":"u49"},
    "17e0417e42f9400d9332619dee87df58":{
      "scriptId":"u50"},
    "fd995b983c814ec1b0a3ffa17426fe15":{
      "scriptId":"u51"},
    "c7b36dab0dd2447dac3ea8a5c5bd123d":{
      "scriptId":"u52"},
    "83f08a9c8978497096de8c8613d34723":{
      "scriptId":"u53"}}});