$axure.loadCurrentPage({
  "url":"中间页交互.html",
  "generationDate":new Date(1480575726837.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"92e0ed96418e40f88be55e9cd4ad059e",
    "type":"Axure:Page",
    "name":"中间页交互",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"60f0aa28ae924cb0829b4ad61af283ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":124},
            "size":{
              "width":321,
              "height":571}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e28535e787b24bce8f808824355f9992",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":124},
                "size":{
                  "width":321,
                  "height":571}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u97.jpg"}},
{
          "id":"cd54ff652f86468ebdc86be57eb9dfb0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":124},
            "size":{
              "width":321,
              "height":571}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08d6da2ae04541868d10b24f457445d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":124},
                "size":{
                  "width":321,
                  "height":571}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u2.jpg"}},
{
          "id":"f9dc37d8bd2449e8920f4da81460ff62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":781,
              "y":124},
            "size":{
              "width":321,
              "height":1606}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da62354604e248f99ff49c9bf186790a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":781,
                  "y":124},
                "size":{
                  "width":321,
                  "height":1606}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u4.jpg"}},
{
          "id":"5c47260b7f3a4790b84229820adad2f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1136,
              "y":124},
            "size":{
              "width":321,
              "height":571}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"755befd8f4ac4bacaf006b3b16d55f64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1136,
                  "y":124},
                "size":{
                  "width":321,
                  "height":571}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u6.jpg"}},
{
          "id":"1f06c3f085fd43b48dac8f9e8759b5c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1489,
              "y":124},
            "size":{
              "width":321,
              "height":571}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c4993bd0454507b36cdac74e96b94e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1489,
                  "y":124},
                "size":{
                  "width":321,
                  "height":571}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u8.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "60f0aa28ae924cb0829b4ad61af283ab":{
      "scriptId":"u0"},
    "e28535e787b24bce8f808824355f9992":{
      "scriptId":"u1"},
    "cd54ff652f86468ebdc86be57eb9dfb0":{
      "scriptId":"u2"},
    "08d6da2ae04541868d10b24f457445d4":{
      "scriptId":"u3"},
    "f9dc37d8bd2449e8920f4da81460ff62":{
      "scriptId":"u4"},
    "da62354604e248f99ff49c9bf186790a":{
      "scriptId":"u5"},
    "5c47260b7f3a4790b84229820adad2f8":{
      "scriptId":"u6"},
    "755befd8f4ac4bacaf006b3b16d55f64":{
      "scriptId":"u7"},
    "1f06c3f085fd43b48dac8f9e8759b5c8":{
      "scriptId":"u8"},
    "61c4993bd0454507b36cdac74e96b94e":{
      "scriptId":"u9"}}});