$axure.loadCurrentPage({
  "url":"我的课程表.html",
  "generationDate":new Date(1480575726041.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ebebebf1aaad4c50b5b9cd3b8318b5ea",
    "type":"Axure:Page",
    "name":"我的课程表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b8069a68b95f40b1acf68e4031e55f4e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":80},
            "size":{
              "width":294,
              "height":479},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a9d87a150d4411baa8680373c961604",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":80},
                "size":{
                  "width":294,
                  "height":479},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的课程表/u0.png"}},
{
          "id":"b7bea3b17b7041cd973b7e88625e216a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":42},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8704de5adc514bbc81c47cbeb63087f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":42},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2050768432543c28d7b8090f1d14aaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":48},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1427a3d2187459da4ebe12da207d6cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":48},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f1a38115e8b484b9971325261956277",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":426,
              "y":80},
            "size":{
              "width":294,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4131d6e251649cb82f9bd8c06157c4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":80},
                "size":{
                  "width":294,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的课程表/u6.png"}},
{
          "id":"1e752bc29feb4010a4528c75fbe8bd07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":217},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7c4837ec8f142e6b89a460ea23cd2a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":217},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4060ff85348a44469c57faa6a1b1a709",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":217},
            "size":{
              "width":80,
              "height":40},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a2d365ccf41435c8295682be1a990eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":217},
                "size":{
                  "width":80,
                  "height":40},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的课程表/u10.png"}},
{
          "id":"920f6a088c9c4e9fbddc4e31d30834bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":330},
            "size":{
              "width":80,
              "height":40},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"431b9e95cf434807a07c382ed9d6f8a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":330},
                "size":{
                  "width":80,
                  "height":40},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的课程表/u10.png"}},
{
          "id":"6d652db74886468c8a64a6be3b5c9677",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":460},
            "size":{
              "width":80,
              "height":40},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cde79aa517e64c20958dbb04c7c19ac8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":460},
                "size":{
                  "width":80,
                  "height":40},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的课程表/u10.png"}},
{
          "id":"b5e8edf8e16a453da54e84ae1530cb52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":130},
            "size":{
              "width":80,
              "height":40},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb9ca86eaa0240b091556deff61e792b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":130},
                "size":{
                  "width":80,
                  "height":40},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的课程表/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b8069a68b95f40b1acf68e4031e55f4e":{
      "scriptId":"u0"},
    "0a9d87a150d4411baa8680373c961604":{
      "scriptId":"u1"},
    "b7bea3b17b7041cd973b7e88625e216a":{
      "scriptId":"u2"},
    "8704de5adc514bbc81c47cbeb63087f5":{
      "scriptId":"u3"},
    "b2050768432543c28d7b8090f1d14aaa":{
      "scriptId":"u4"},
    "b1427a3d2187459da4ebe12da207d6cf":{
      "scriptId":"u5"},
    "8f1a38115e8b484b9971325261956277":{
      "scriptId":"u6"},
    "a4131d6e251649cb82f9bd8c06157c4f":{
      "scriptId":"u7"},
    "1e752bc29feb4010a4528c75fbe8bd07":{
      "scriptId":"u8"},
    "e7c4837ec8f142e6b89a460ea23cd2a1":{
      "scriptId":"u9"},
    "4060ff85348a44469c57faa6a1b1a709":{
      "scriptId":"u10"},
    "0a2d365ccf41435c8295682be1a990eb":{
      "scriptId":"u11"},
    "920f6a088c9c4e9fbddc4e31d30834bf":{
      "scriptId":"u12"},
    "431b9e95cf434807a07c382ed9d6f8a5":{
      "scriptId":"u13"},
    "6d652db74886468c8a64a6be3b5c9677":{
      "scriptId":"u14"},
    "cde79aa517e64c20958dbb04c7c19ac8":{
      "scriptId":"u15"},
    "b5e8edf8e16a453da54e84ae1530cb52":{
      "scriptId":"u16"},
    "bb9ca86eaa0240b091556deff61e792b":{
      "scriptId":"u17"}}});