$axure.loadCurrentPage({
  "url":"应用配置的引导页简化.html",
  "generationDate":new Date(1484217175640.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9784738caf53465d93e5fd779f364d7a",
    "type":"Axure:Page",
    "name":"应用配置的引导页简化",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f3b2a4647a3b4859bf9a53f377d47774",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":540},
            "size":{
              "width":321,
              "height":106},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c29f22093004559990938db4c08ed9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":540},
                "size":{
                  "width":321,
                  "height":106},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u0.png"}},
{
          "id":"1d28248c920046f8b19a222b8da5823e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":541},
            "size":{
              "width":321,
              "height":106},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e29f1e7f39446498456de2e5173f8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":541},
                "size":{
                  "width":321,
                  "height":106},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u0.png"}},
{
          "id":"ad45767845ea453397a2cd2636ccf8a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":83},
            "size":{
              "width":321,
              "height":213},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8138bd4667374492947863957f4bbd58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":83},
                "size":{
                  "width":321,
                  "height":213},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u4.png"}},
{
          "id":"f56cea6ef7ee485dab193ae43db0c8f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":400},
            "size":{
              "width":321,
              "height":141},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b6da1c854854dffaa928d6562bb4bbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":400},
                "size":{
                  "width":321,
                  "height":141},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u6.png"}},
{
          "id":"b8920b4a5e724d0fa1bf8bf4d82f7032",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":295},
            "size":{
              "width":321,
              "height":35},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36ed3f9a3b0945658808e921977a76c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":295},
                "size":{
                  "width":321,
                  "height":35},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u8.png"}},
{
          "id":"c91c02131af34a4da12f32214fed83ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":330},
            "size":{
              "width":321,
              "height":106},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a4674ca1083442c84dfc97a2e5ece63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":330},
                "size":{
                  "width":321,
                  "height":106},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u0.png"}},
{
          "id":"5112f81ec6884fb08685475689e49645",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":295},
            "size":{
              "width":179,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea47c6d1c6014b56a93192db78d992d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":136,
                  "y":295},
                "size":{
                  "width":179,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u12.png"}},
{
          "id":"3b3f9da9d75749748c767e1f0f7f07e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":538},
            "size":{
              "width":321,
              "height":109},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f5ab9551cda4ca6940fb8ac7c41d24f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":538},
                "size":{
                  "width":321,
                  "height":109},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u14.png"}},
{
          "id":"a7d9ff44d041476abad8355a8ab9b0ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":42},
            "size":{
              "width":73,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b61c2b16c482452288016764b0295c04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":42},
                "size":{
                  "width":73,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1a8c61d8d3a4d358ee40f660deb67c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x66000000},
            "location":{
              "x":70,
              "y":330},
            "size":{
              "width":321,
              "height":320},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c196a4970b7b4935b91c823a99114c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x66000000},
                "location":{
                  "x":70,
                  "y":330},
                "size":{
                  "width":321,
                  "height":320},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u18.png"}},
{
          "id":"f2250c43733349ceafb564e554a704fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":84},
            "size":{
              "width":321,
              "height":212},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84b5198b320240fa83cfe340f6124106",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":84},
                "size":{
                  "width":321,
                  "height":212},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u20.png"}},
{
          "id":"2581c3c6f99c44ad9334c99a1ac7731b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x99000000},
            "location":{
              "x":70,
              "y":84},
            "size":{
              "width":321,
              "height":564}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29d7114eae2e45e291fa74784fde5e0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x99000000},
                "location":{
                  "x":70,
                  "y":84},
                "size":{
                  "width":321,
                  "height":564}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u22.png"}},
{
          "id":"334a75ef855d42ec921d38ee8cb91818",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":85},
            "size":{
              "width":32,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"16",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.776470588235294}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b1a0eb3349b4c0ebe523287ee9b765f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":85},
                "size":{
                  "width":32,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"16",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.776470588235294}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u24.png"}},
{
          "id":"8e891fb8f5094a1bb77b024fdea7deb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":85},
            "size":{
              "width":32,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"16",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.776470588235294}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b47fa64ca46340d3879d1e02570e7c61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":85},
                "size":{
                  "width":32,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"16",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.776470588235294}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u24.png"}},
{
          "id":"09338300420d4a68a1a762f0b8d63543",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":85},
            "size":{
              "width":32,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"16",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.776470588235294}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"647aa2987a304392888fe8afaad58424",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":85},
                "size":{
                  "width":32,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"16",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.776470588235294}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u24.png"}},
{
          "id":"6f89692b85e04632b1762dd1869ad70d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":191},
            "size":{
              "width":32,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"16",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.776470588235294}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c28314a524e54e4eac5b3059a2d43ab4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":191},
                "size":{
                  "width":32,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"16",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.776470588235294}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u24.png"}},
{
          "id":"d60bb2f6b094469f9f03970190205758",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":191},
            "size":{
              "width":32,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"16",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.776470588235294}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c46f2f0a7b640f0a53ac3e52d80bc57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":191},
                "size":{
                  "width":32,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"16",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.776470588235294}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u24.png"}},
{
          "id":"5cc3640b653741589c9d949556c641ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":191},
            "size":{
              "width":32,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"16",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.776470588235294}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00943fa4a06b483f832cc9e11bbdb990",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":191},
                "size":{
                  "width":32,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"16",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.776470588235294}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u24.png"}},
{
          "id":"afc6b9819f8b43788fd71b9b5baa5846",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":138,
              "y":407},
            "size":{
              "width":187,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d111fa2584ba4ed3b90f916ae8c9c46e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":407},
                "size":{
                  "width":187,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f2b1bde5fda47b4b945656687efbbaa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":402},
            "size":{
              "width":32,
              "height":32},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"16",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":2,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.776470588235294}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c6f42ddaf3745bf8457aed57a4b6b6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":402},
                "size":{
                  "width":32,
                  "height":32},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"16",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":2,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.776470588235294}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u24.png"}},
{
          "id":"b05834b22106450baf67a14e835f6a2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":83},
            "size":{
              "width":321,
              "height":213},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15d5c12a35f24b1c8c5c4ddeaf6b77ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":83},
                "size":{
                  "width":321,
                  "height":213},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u4.png"}},
{
          "id":"e89ad9b7310c4fd189e02e657061c275",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":400},
            "size":{
              "width":321,
              "height":141},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df03bc25e6974e30822c248addb8761f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":400},
                "size":{
                  "width":321,
                  "height":141},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u6.png"}},
{
          "id":"462a6a98157249d4809903eb8dc013a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":295},
            "size":{
              "width":321,
              "height":141},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"862e5c780cf64cd8ba7996939a18eb0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":295},
                "size":{
                  "width":321,
                  "height":141},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u6.png"}},
{
          "id":"0e7cb6e4989a425789fdf392946ca393",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":488,
              "y":295},
            "size":{
              "width":179,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5057b057fee462db9ec55627992f264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":488,
                  "y":295},
                "size":{
                  "width":179,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u12.png"}},
{
          "id":"d012e77efd5e4072bc697d4346622967",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":84},
            "size":{
              "width":321,
              "height":212},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5292a599ab7641d19f8a66e39d38aa65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":84},
                "size":{
                  "width":321,
                  "height":212},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u20.png"}},
{
          "id":"5ad4939ea7ee44189925b5129b2cc447",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":187},
            "size":{
              "width":321,
              "height":109},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcf2a789202f47a2b58d62e5a4895e60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":187},
                "size":{
                  "width":321,
                  "height":109},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u50.png"}},
{
          "id":"f9d4b9a674114d5a9fcd4be33c7d2d4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":136,
              "y":556},
            "size":{
              "width":200,
              "height":50},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08ae60025c9541afa4f84d6c12caa95a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":556},
                "size":{
                  "width":200,
                  "height":50},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u52.png"}},
{
          "id":"39b33354c75d46b2849f6161e41f9c07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":537},
            "size":{
              "width":321,
              "height":109},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e26eb2895788434c93dd3044ec1bd196",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":537},
                "size":{
                  "width":321,
                  "height":109},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u14.png"}},
{
          "id":"e857b3eb1e364a588af43cbf58c251ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xB2000000},
            "location":{
              "x":424,
              "y":83},
            "size":{
              "width":321,
              "height":251},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ea35c03a953493999197afe3508da98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xB2000000},
                "location":{
                  "x":424,
                  "y":83},
                "size":{
                  "width":321,
                  "height":251},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u56.png"}},
{
          "id":"f171c3aa5f9349deb50b4c329b10e3f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x99000000},
            "location":{
              "x":424,
              "y":82},
            "size":{
              "width":321,
              "height":564}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d28c723de35418894704b796ad6b7eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x99000000},
                "location":{
                  "x":424,
                  "y":82},
                "size":{
                  "width":321,
                  "height":564}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u22.png"}},
{
          "id":"7d843e53762b42cd9d03c00b3a86b663",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":488,
              "y":121},
            "size":{
              "width":193,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b831bbe7ead847d8b0b056bad47efb1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":121},
                "size":{
                  "width":193,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6bd2ed7bca14708bbdbafad2d1d4758",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":484,
              "y":212},
            "size":{
              "width":200,
              "height":43},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05019b66aa4a4cfbb996c3e20d859120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":484,
                  "y":212},
                "size":{
                  "width":200,
                  "height":43},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u62.png"}},
{
          "id":"1e18de1d70bf4298adf7734479b73103",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":334},
            "size":{
              "width":31,
              "height":30},
            "cornerRadiusTopLeft":"63",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88456524fb7f4ce1a666abac4d9e2024",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":334},
                "size":{
                  "width":31,
                  "height":30},
                "cornerRadiusTopLeft":"63",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u64.png"}},
{
          "id":"94fcf881058d4176bef760744f495dc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":602,
              "y":334},
            "size":{
              "width":31,
              "height":30},
            "cornerRadiusTopLeft":"63",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0148d847eb044a4bb32cce79e588bbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":602,
                  "y":334},
                "size":{
                  "width":31,
                  "height":30},
                "cornerRadiusTopLeft":"63",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u64.png"}},
{
          "id":"883e0c4fb9e2466bbf34f5a890927c0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":334},
            "size":{
              "width":31,
              "height":30},
            "cornerRadiusTopLeft":"63",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bd87f360e7b47dea1a2e423bd7ac985",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":334},
                "size":{
                  "width":31,
                  "height":30},
                "cornerRadiusTopLeft":"63",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u64.png"}},
{
          "id":"8a52de79ea83438ba8b89780f4aa2d14",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":438},
            "size":{
              "width":31,
              "height":30},
            "cornerRadiusTopLeft":"63",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8431207ec0e47a2a5a3dce9f9364162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":438},
                "size":{
                  "width":31,
                  "height":30},
                "cornerRadiusTopLeft":"63",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u64.png"}},
{
          "id":"7d1b06604d18444b9e659e44688fea20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":602,
              "y":438},
            "size":{
              "width":31,
              "height":30},
            "cornerRadiusTopLeft":"63",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2201edfd0594a4a835f87b44d79824e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":602,
                  "y":438},
                "size":{
                  "width":31,
                  "height":30},
                "cornerRadiusTopLeft":"63",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u64.png"}},
{
          "id":"7d50f91f67874624930c5085eda6181b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":438},
            "size":{
              "width":31,
              "height":30},
            "cornerRadiusTopLeft":"63",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"568b21523cd94d79ad478729ef49155f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":438},
                "size":{
                  "width":31,
                  "height":30},
                "cornerRadiusTopLeft":"63",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u64.png"}},
{
          "id":"7f47455ca12a443393a904d112a4b28b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":544},
            "size":{
              "width":31,
              "height":30},
            "cornerRadiusTopLeft":"63",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24e8a010e3494fc2a29daa0c6ae63ef2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":544},
                "size":{
                  "width":31,
                  "height":30},
                "cornerRadiusTopLeft":"63",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u64.png"}},
{
          "id":"5641675c6bc246aea90caf4ea5ff3519",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":602,
              "y":544},
            "size":{
              "width":31,
              "height":30},
            "cornerRadiusTopLeft":"63",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f6a0e3781ba4b228f7ca623f2c1af89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":602,
                  "y":544},
                "size":{
                  "width":31,
                  "height":30},
                "cornerRadiusTopLeft":"63",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u64.png"}},
{
          "id":"9ceb54f0d8414916b90ab870f7df76e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":544},
            "size":{
              "width":31,
              "height":30},
            "cornerRadiusTopLeft":"63",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ed54e427df4b73b973ff227ce79c9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":544},
                "size":{
                  "width":31,
                  "height":30},
                "cornerRadiusTopLeft":"63",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u64.png"}},
{
          "id":"06d57bbea3834a93937e16833e00ad7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":118},
            "size":{
              "width":31,
              "height":30},
            "cornerRadiusTopLeft":"63",
            "outerShadow":{
              "on":true,
              "offsetX":3,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":255,
                "g":255,
                "b":255,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ee96d0f973e49b18be9d5cb062b9897",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":118},
                "size":{
                  "width":31,
                  "height":30},
                "cornerRadiusTopLeft":"63",
                "outerShadow":{
                  "on":true,
                  "offsetX":3,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":255,
                    "g":255,
                    "b":255,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u64.png"}},
{
          "id":"8c201b4480e346919540584eb3984e86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":512,
              "y":304},
            "size":{
              "width":154,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"939d822dc1f14f0ba78b3a0f90a710b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":512,
                  "y":304},
                "size":{
                  "width":154,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"760d0b9fd24642f49dc3d9b0c47d4341",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":158,
              "y":304},
            "size":{
              "width":154,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfdf60c47b984f299b0770dcbd667937",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":158,
                  "y":304},
                "size":{
                  "width":154,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf1ad69281bd4171be969336dc2da6aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":313,
              "y":44},
            "size":{
              "width":289,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20f61dc9fcd84345b79997c370d93fc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":313,
                  "y":44},
                "size":{
                  "width":289,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5434fec2453c4ed5be3ff5f725b15386",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":83},
            "size":{
              "width":321,
              "height":213},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8078bb82053845dba522e6ed7f3addcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":83},
                "size":{
                  "width":321,
                  "height":213},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u4.png"}},
{
          "id":"b9488801d2d844d593a3137d56206ed0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":401},
            "size":{
              "width":321,
              "height":141},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0629e8473a9f483b83bcfc0eae262f1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":401},
                "size":{
                  "width":321,
                  "height":141},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u6.png"}},
{
          "id":"18295266c53543ceab65524fa8d8240a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":541},
            "size":{
              "width":321,
              "height":109},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f98367bbf2444afca989b1bebdb638db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":541},
                "size":{
                  "width":321,
                  "height":109},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u14.png"}},
{
          "id":"24ff8841dc2b4ff9855851a88e77fb89",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":922,
              "y":43},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f0973ed0bd04041b9b5a6477087a067",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":922,
                  "y":43},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35762f944a5144c9a6ca7e52ea26d381",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":295},
            "size":{
              "width":321,
              "height":141},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c682c106608d49629ed3b91b74478b38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":295},
                "size":{
                  "width":321,
                  "height":141},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u6.png"}},
{
          "id":"97772772ac334399b688f359753ffcae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":875,
              "y":295},
            "size":{
              "width":179,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffd53bd8155e4871b8322eba6fa41329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":875,
                  "y":295},
                "size":{
                  "width":179,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u12.png"}},
{
          "id":"75797548fcae4ef588a2ef1a9ec096c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":898,
              "y":305},
            "size":{
              "width":154,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f98e4f88153a4c738fcb22643d26bca7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":898,
                  "y":305},
                "size":{
                  "width":154,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"552a3803c35d4dd4b53bdf665b8dc793",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":875,
              "y":331},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0166a001610644ee9e8a51eeaa293206",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":875,
                  "y":331},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u104.png"}},
{
          "id":"e81d786c1b6a48478d8987cb9acd8682",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":875,
              "y":435},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87e687afbfcd4df9823ae0c7a3b0594d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":875,
                  "y":435},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u104.png"}},
{
          "id":"d3710846dc83499ea0a4704ed1f18b56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":984,
              "y":329},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51286ec903054a6790534401ed7c84cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":984,
                  "y":329},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u104.png"}},
{
          "id":"4af102c261f6447a93d3d9fcd66b673e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":984,
              "y":435},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d29b85bbff994ff5b0f5802a0cf3ac3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":984,
                  "y":435},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u104.png"}},
{
          "id":"8335871883b04f46bddc15ad8c45838f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1094,
              "y":331},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"256624ff2f6d40ebb63c31ad1ba035c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1094,
                  "y":331},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u104.png"}},
{
          "id":"10de415e335e4272a1c46b1a9c40b5c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1094,
              "y":435},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45df239859474deeaded3f9b44987222",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1094,
                  "y":435},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u104.png"}},
{
          "id":"d63762ac88264c8eba3e86b81927336f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1096,
              "y":541},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eafd53610acb4b0da4708e607115acbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1096,
                  "y":541},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u104.png"}},
{
          "id":"701e51e97e1a475190514d17dcd8ad79",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":984,
              "y":541},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9afd4b265ddd408fb36bb5f6c592f529",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":984,
                  "y":541},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u104.png"}},
{
          "id":"5e1fa5118c4441bda288821bf6e85464",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":875,
              "y":537},
            "size":{
              "width":35,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8e21825ba1f4ed290b669e18544a23f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":875,
                  "y":537},
                "size":{
                  "width":35,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用配置的引导页简化/u104.png"}},
{
          "id":"bc42b317b3c14841945381757c1121c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1035,
              "y":25},
            "size":{
              "width":455,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be63ae31995441f7852dbe7ec577bcb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1035,
                  "y":25},
                "size":{
                  "width":455,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f3b2a4647a3b4859bf9a53f377d47774":{
      "scriptId":"u0"},
    "6c29f22093004559990938db4c08ed9c":{
      "scriptId":"u1"},
    "1d28248c920046f8b19a222b8da5823e":{
      "scriptId":"u2"},
    "76e29f1e7f39446498456de2e5173f8f":{
      "scriptId":"u3"},
    "ad45767845ea453397a2cd2636ccf8a0":{
      "scriptId":"u4"},
    "8138bd4667374492947863957f4bbd58":{
      "scriptId":"u5"},
    "f56cea6ef7ee485dab193ae43db0c8f0":{
      "scriptId":"u6"},
    "0b6da1c854854dffaa928d6562bb4bbc":{
      "scriptId":"u7"},
    "b8920b4a5e724d0fa1bf8bf4d82f7032":{
      "scriptId":"u8"},
    "36ed3f9a3b0945658808e921977a76c5":{
      "scriptId":"u9"},
    "c91c02131af34a4da12f32214fed83ce":{
      "scriptId":"u10"},
    "2a4674ca1083442c84dfc97a2e5ece63":{
      "scriptId":"u11"},
    "5112f81ec6884fb08685475689e49645":{
      "scriptId":"u12"},
    "ea47c6d1c6014b56a93192db78d992d8":{
      "scriptId":"u13"},
    "3b3f9da9d75749748c767e1f0f7f07e0":{
      "scriptId":"u14"},
    "1f5ab9551cda4ca6940fb8ac7c41d24f":{
      "scriptId":"u15"},
    "a7d9ff44d041476abad8355a8ab9b0ff":{
      "scriptId":"u16"},
    "b61c2b16c482452288016764b0295c04":{
      "scriptId":"u17"},
    "c1a8c61d8d3a4d358ee40f660deb67c6":{
      "scriptId":"u18"},
    "c196a4970b7b4935b91c823a99114c63":{
      "scriptId":"u19"},
    "f2250c43733349ceafb564e554a704fe":{
      "scriptId":"u20"},
    "84b5198b320240fa83cfe340f6124106":{
      "scriptId":"u21"},
    "2581c3c6f99c44ad9334c99a1ac7731b":{
      "scriptId":"u22"},
    "29d7114eae2e45e291fa74784fde5e0c":{
      "scriptId":"u23"},
    "334a75ef855d42ec921d38ee8cb91818":{
      "scriptId":"u24"},
    "0b1a0eb3349b4c0ebe523287ee9b765f":{
      "scriptId":"u25"},
    "8e891fb8f5094a1bb77b024fdea7deb6":{
      "scriptId":"u26"},
    "b47fa64ca46340d3879d1e02570e7c61":{
      "scriptId":"u27"},
    "09338300420d4a68a1a762f0b8d63543":{
      "scriptId":"u28"},
    "647aa2987a304392888fe8afaad58424":{
      "scriptId":"u29"},
    "6f89692b85e04632b1762dd1869ad70d":{
      "scriptId":"u30"},
    "c28314a524e54e4eac5b3059a2d43ab4":{
      "scriptId":"u31"},
    "d60bb2f6b094469f9f03970190205758":{
      "scriptId":"u32"},
    "2c46f2f0a7b640f0a53ac3e52d80bc57":{
      "scriptId":"u33"},
    "5cc3640b653741589c9d949556c641ab":{
      "scriptId":"u34"},
    "00943fa4a06b483f832cc9e11bbdb990":{
      "scriptId":"u35"},
    "afc6b9819f8b43788fd71b9b5baa5846":{
      "scriptId":"u36"},
    "d111fa2584ba4ed3b90f916ae8c9c46e":{
      "scriptId":"u37"},
    "8f2b1bde5fda47b4b945656687efbbaa":{
      "scriptId":"u38"},
    "3c6f42ddaf3745bf8457aed57a4b6b6f":{
      "scriptId":"u39"},
    "b05834b22106450baf67a14e835f6a2a":{
      "scriptId":"u40"},
    "15d5c12a35f24b1c8c5c4ddeaf6b77ae":{
      "scriptId":"u41"},
    "e89ad9b7310c4fd189e02e657061c275":{
      "scriptId":"u42"},
    "df03bc25e6974e30822c248addb8761f":{
      "scriptId":"u43"},
    "462a6a98157249d4809903eb8dc013a5":{
      "scriptId":"u44"},
    "862e5c780cf64cd8ba7996939a18eb0c":{
      "scriptId":"u45"},
    "0e7cb6e4989a425789fdf392946ca393":{
      "scriptId":"u46"},
    "f5057b057fee462db9ec55627992f264":{
      "scriptId":"u47"},
    "d012e77efd5e4072bc697d4346622967":{
      "scriptId":"u48"},
    "5292a599ab7641d19f8a66e39d38aa65":{
      "scriptId":"u49"},
    "5ad4939ea7ee44189925b5129b2cc447":{
      "scriptId":"u50"},
    "dcf2a789202f47a2b58d62e5a4895e60":{
      "scriptId":"u51"},
    "f9d4b9a674114d5a9fcd4be33c7d2d4d":{
      "scriptId":"u52"},
    "08ae60025c9541afa4f84d6c12caa95a":{
      "scriptId":"u53"},
    "39b33354c75d46b2849f6161e41f9c07":{
      "scriptId":"u54"},
    "e26eb2895788434c93dd3044ec1bd196":{
      "scriptId":"u55"},
    "e857b3eb1e364a588af43cbf58c251ad":{
      "scriptId":"u56"},
    "3ea35c03a953493999197afe3508da98":{
      "scriptId":"u57"},
    "f171c3aa5f9349deb50b4c329b10e3f0":{
      "scriptId":"u58"},
    "8d28c723de35418894704b796ad6b7eb":{
      "scriptId":"u59"},
    "7d843e53762b42cd9d03c00b3a86b663":{
      "scriptId":"u60"},
    "b831bbe7ead847d8b0b056bad47efb1a":{
      "scriptId":"u61"},
    "a6bd2ed7bca14708bbdbafad2d1d4758":{
      "scriptId":"u62"},
    "05019b66aa4a4cfbb996c3e20d859120":{
      "scriptId":"u63"},
    "1e18de1d70bf4298adf7734479b73103":{
      "scriptId":"u64"},
    "88456524fb7f4ce1a666abac4d9e2024":{
      "scriptId":"u65"},
    "94fcf881058d4176bef760744f495dc1":{
      "scriptId":"u66"},
    "b0148d847eb044a4bb32cce79e588bbf":{
      "scriptId":"u67"},
    "883e0c4fb9e2466bbf34f5a890927c0e":{
      "scriptId":"u68"},
    "6bd87f360e7b47dea1a2e423bd7ac985":{
      "scriptId":"u69"},
    "8a52de79ea83438ba8b89780f4aa2d14":{
      "scriptId":"u70"},
    "d8431207ec0e47a2a5a3dce9f9364162":{
      "scriptId":"u71"},
    "7d1b06604d18444b9e659e44688fea20":{
      "scriptId":"u72"},
    "c2201edfd0594a4a835f87b44d79824e":{
      "scriptId":"u73"},
    "7d50f91f67874624930c5085eda6181b":{
      "scriptId":"u74"},
    "568b21523cd94d79ad478729ef49155f":{
      "scriptId":"u75"},
    "7f47455ca12a443393a904d112a4b28b":{
      "scriptId":"u76"},
    "24e8a010e3494fc2a29daa0c6ae63ef2":{
      "scriptId":"u77"},
    "5641675c6bc246aea90caf4ea5ff3519":{
      "scriptId":"u78"},
    "7f6a0e3781ba4b228f7ca623f2c1af89":{
      "scriptId":"u79"},
    "9ceb54f0d8414916b90ab870f7df76e9":{
      "scriptId":"u80"},
    "d5ed54e427df4b73b973ff227ce79c9c":{
      "scriptId":"u81"},
    "06d57bbea3834a93937e16833e00ad7f":{
      "scriptId":"u82"},
    "5ee96d0f973e49b18be9d5cb062b9897":{
      "scriptId":"u83"},
    "8c201b4480e346919540584eb3984e86":{
      "scriptId":"u84"},
    "939d822dc1f14f0ba78b3a0f90a710b2":{
      "scriptId":"u85"},
    "760d0b9fd24642f49dc3d9b0c47d4341":{
      "scriptId":"u86"},
    "dfdf60c47b984f299b0770dcbd667937":{
      "scriptId":"u87"},
    "bf1ad69281bd4171be969336dc2da6aa":{
      "scriptId":"u88"},
    "20f61dc9fcd84345b79997c370d93fc0":{
      "scriptId":"u89"},
    "5434fec2453c4ed5be3ff5f725b15386":{
      "scriptId":"u90"},
    "8078bb82053845dba522e6ed7f3addcb":{
      "scriptId":"u91"},
    "b9488801d2d844d593a3137d56206ed0":{
      "scriptId":"u92"},
    "0629e8473a9f483b83bcfc0eae262f1f":{
      "scriptId":"u93"},
    "18295266c53543ceab65524fa8d8240a":{
      "scriptId":"u94"},
    "f98367bbf2444afca989b1bebdb638db":{
      "scriptId":"u95"},
    "24ff8841dc2b4ff9855851a88e77fb89":{
      "scriptId":"u96"},
    "1f0973ed0bd04041b9b5a6477087a067":{
      "scriptId":"u97"},
    "35762f944a5144c9a6ca7e52ea26d381":{
      "scriptId":"u98"},
    "c682c106608d49629ed3b91b74478b38":{
      "scriptId":"u99"},
    "97772772ac334399b688f359753ffcae":{
      "scriptId":"u100"},
    "ffd53bd8155e4871b8322eba6fa41329":{
      "scriptId":"u101"},
    "75797548fcae4ef588a2ef1a9ec096c0":{
      "scriptId":"u102"},
    "f98e4f88153a4c738fcb22643d26bca7":{
      "scriptId":"u103"},
    "552a3803c35d4dd4b53bdf665b8dc793":{
      "scriptId":"u104"},
    "0166a001610644ee9e8a51eeaa293206":{
      "scriptId":"u105"},
    "e81d786c1b6a48478d8987cb9acd8682":{
      "scriptId":"u106"},
    "87e687afbfcd4df9823ae0c7a3b0594d":{
      "scriptId":"u107"},
    "d3710846dc83499ea0a4704ed1f18b56":{
      "scriptId":"u108"},
    "51286ec903054a6790534401ed7c84cd":{
      "scriptId":"u109"},
    "4af102c261f6447a93d3d9fcd66b673e":{
      "scriptId":"u110"},
    "d29b85bbff994ff5b0f5802a0cf3ac3e":{
      "scriptId":"u111"},
    "8335871883b04f46bddc15ad8c45838f":{
      "scriptId":"u112"},
    "256624ff2f6d40ebb63c31ad1ba035c2":{
      "scriptId":"u113"},
    "10de415e335e4272a1c46b1a9c40b5c2":{
      "scriptId":"u114"},
    "45df239859474deeaded3f9b44987222":{
      "scriptId":"u115"},
    "d63762ac88264c8eba3e86b81927336f":{
      "scriptId":"u116"},
    "eafd53610acb4b0da4708e607115acbf":{
      "scriptId":"u117"},
    "701e51e97e1a475190514d17dcd8ad79":{
      "scriptId":"u118"},
    "9afd4b265ddd408fb36bb5f6c592f529":{
      "scriptId":"u119"},
    "5e1fa5118c4441bda288821bf6e85464":{
      "scriptId":"u120"},
    "a8e21825ba1f4ed290b669e18544a23f":{
      "scriptId":"u121"},
    "bc42b317b3c14841945381757c1121c8":{
      "scriptId":"u122"},
    "be63ae31995441f7852dbe7ec577bcb1":{
      "scriptId":"u123"}}});