$axure.loadCurrentPage({
  "url":"私人医生.html",
  "generationDate":new Date(1480996652534.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"895858fa242147daaf7a46180fa91c13",
    "type":"Axure:Page",
    "name":"私人医生",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"42aef7ec40c44aa7bebe3f0b8162fdc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":72},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88aebb960c1942aa8668091c9502800b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":72},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0002c0f8a39c46dcb21aea6490bfb7fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":50},
            "size":{
              "width":281,
              "height":460},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89d252cb289e49ecbe522b80e92533fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":50},
                "size":{
                  "width":281,
                  "height":460},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/私人医生/u2.png"}},
{
          "id":"1c232e4a24cc4f5280209e312285cb63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":63},
            "size":{
              "width":20,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b44c94eaa015460b8478a67120933279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":63},
                "size":{
                  "width":20,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "42aef7ec40c44aa7bebe3f0b8162fdc6":{
      "scriptId":"u0"},
    "88aebb960c1942aa8668091c9502800b":{
      "scriptId":"u1"},
    "0002c0f8a39c46dcb21aea6490bfb7fc":{
      "scriptId":"u2"},
    "89d252cb289e49ecbe522b80e92533fe":{
      "scriptId":"u3"},
    "1c232e4a24cc4f5280209e312285cb63":{
      "scriptId":"u4"},
    "b44c94eaa015460b8478a67120933279":{
      "scriptId":"u5"}}});