$axure.loadCurrentPage({
  "url":"自我诊断.html",
  "generationDate":new Date(1483009543133.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ded486c7e7bd4fda905198a4336813c8",
    "type":"Axure:Page",
    "name":"自我诊断",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0947bfac6e3b4d48b990f5392e2133bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1598,
              "y":60},
            "size":{
              "width":278,
              "height":455},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31c8ddab648d444dabbd16b281db4232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1598,
                  "y":60},
                "size":{
                  "width":278,
                  "height":455},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u0.png"}},
{
          "id":"bd5566a029ec492b9ff6066697c81479",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":476,
              "y":60},
            "size":{
              "width":278,
              "height":455},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7811b4592954948a5061e25083df7ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":476,
                  "y":60},
                "size":{
                  "width":278,
                  "height":455},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u0.png"}},
{
          "id":"59682601e90b41c3baf09cf28d3ea3a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":60},
            "size":{
              "width":283,
              "height":38},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c36f9da3b23e44598100aa4b46aa502a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":60},
                "size":{
                  "width":283,
                  "height":38},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u4.png"}},
{
          "id":"5555b80bbd3a4c94bf1e122aa926e4ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":98},
            "size":{
              "width":283,
              "height":417},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf12d9df6e3d462f85d0596ef7cb2e01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":98},
                "size":{
                  "width":283,
                  "height":417},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u6.png"}},
{
          "id":"4ceb6fa67ade4b6798c2c83bac1d8ba6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":108},
            "size":{
              "width":266,
              "height":378}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f821c2c1d134e258615123c56d11f6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":108},
                "size":{
                  "width":266,
                  "height":378}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u8.png"}},
{
          "id":"b0164c55d0c8406a853986a280b67fce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":230},
            "size":{
              "width":283,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/自我诊断/u10_line.png"}},
{
          "id":"35a4e4717e2949949830ca6f9668e979",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":379},
            "size":{
              "width":283,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/自我诊断/u10_line.png"}},
{
          "id":"99392e7441204126a6331dd7529848b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":121},
            "size":{
              "width":93,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc9a22b013f74fc5a03ab692ed5486fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":121},
                "size":{
                  "width":93,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u12.png"}},
{
          "id":"e576823d17e44f6b8990d97879a98f80",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":202,
              "y":137},
            "size":{
              "width":111,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"692b6c531b84492485ee4d4bac858e65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":202,
                  "y":137},
                "size":{
                  "width":111,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2685895a9d2b478893c9007b07d07ef2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":266},
            "size":{
              "width":84,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70761e01f560429a9bfb7b22c5582918",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":266},
                "size":{
                  "width":84,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u16.png"}},
{
          "id":"072e8a85efaa4bb1828750014856c712",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":202,
              "y":283},
            "size":{
              "width":111,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d872e0a01ca4cbd81f52ee741bbf7c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":202,
                  "y":283},
                "size":{
                  "width":111,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2ec23b082834dbfbb1baf6fe5c37a5b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":404},
            "size":{
              "width":84,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5653a57cfa7f474892ca4f4b6a87fea9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":404},
                "size":{
                  "width":84,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u20.png"}},
{
          "id":"4c90cd87f5774ac2897c1421f70ec615",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":202,
              "y":423},
            "size":{
              "width":111,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ccff76863904db28a22da3433041d94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":202,
                  "y":423},
                "size":{
                  "width":111,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db3e2ea70e7c44cc978611b20e153d8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":202,
              "y":167},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4f0eee668044e0f88741645d354f696",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":202,
                  "y":167},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4c0ec784b3546bcb7873407cf480d1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":202,
              "y":313},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2372ef2067ad4bc6b6a27a44169fefde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":202,
                  "y":313},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0de89fec292e4c989578132966973911",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":202,
              "y":453},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a18c9db504494d9b9858761c3c77f390",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":202,
                  "y":453},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b4724118b5e4fa1ba732832df15a1ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":202,
              "y":481},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bf7e663dd1e4a6eb1b2b71d86b87cc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":202,
                  "y":481},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"662920a9f02442458960b7bbe41fb299",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":478,
              "y":72},
            "size":{
              "width":273,
              "height":404}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7600d7181aef4e3f9cdae76520874d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":478,
                  "y":72},
                "size":{
                  "width":273,
                  "height":404}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u32.png"}},
{
          "id":"76af810d5b264f3f9d415eda10f8386d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFEFEEEC},
            "location":{
              "x":850,
              "y":60},
            "size":{
              "width":278,
              "height":455},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c50f4232b6bc40f89ffdf929a66165c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEFEEEC},
                "location":{
                  "x":850,
                  "y":60},
                "size":{
                  "width":278,
                  "height":455},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u34.png"}},
{
          "id":"654bba6de4b54626aa19f5fb4ebf824d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":852,
              "y":72},
            "size":{
              "width":275,
              "height":374},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb5bb294b1244088b090ac2d8face05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":852,
                  "y":72},
                "size":{
                  "width":275,
                  "height":374},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u36.png"}},
{
          "id":"65b55bd9e1714f7ab734b962267078c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1603,
              "y":64},
            "size":{
              "width":271,
              "height":447},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b4905fa9aa413a9beff08f7d1eb9be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1603,
                  "y":64},
                "size":{
                  "width":271,
                  "height":447},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u38.png"}},
{
          "id":"679919d7fd604655818543c5435ef7d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1224,
              "y":60},
            "size":{
              "width":278,
              "height":455},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c732db8f64094863bffb19b5d725738c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1224,
                  "y":60},
                "size":{
                  "width":278,
                  "height":455},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u0.png"}},
{
          "id":"956bec501cbc45858f5934cb431208cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1225,
              "y":66},
            "size":{
              "width":276,
              "height":404},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"347ad237e12047fe9bb102c948913292",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1225,
                  "y":66},
                "size":{
                  "width":276,
                  "height":404},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u42.png"}},
{
          "id":"a6bccc05c56144e5a39c5a9457ca8c73",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":852,
              "y":61},
            "size":{
              "width":275,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50658236d226435cbd3a624b636da585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":852,
                  "y":61},
                "size":{
                  "width":275,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u44.png"}},
{
          "id":"1441c46f00fa410d802c43ad09edfbdf",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":157},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35bea99a0a284a80bd9b6f3247be177a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":341,
                  "y":157},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}]},
{
          "id":"45c93d267f8e4e3eb14c105f1c822273",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":334,
              "y":141},
            "size":{
              "width":118,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abd3605c249948e4862430339c3bec9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":334,
                  "y":141},
                "size":{
                  "width":118,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e517dd89f410462a837e6e7ffaebcbec",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":451,
              "y":25},
            "size":{
              "width":10,
              "height":535},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/自我诊断/u50_line.png"}},
{
          "id":"17ea015f6ffb4e27bfdc4f1e5f891641",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":928,
              "y":319},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35e0cd993db5462491c34f50b3d1c44d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":928,
                  "y":319},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"078ac9217652493f9a401daece837ca1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":854,
              "y":25},
            "size":{
              "width":275,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f699f01b413454093390970d65e6d83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":854,
                  "y":25},
                "size":{
                  "width":275,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56c6159b4b084b278256fc82f3509f40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1227,
              "y":431},
            "size":{
              "width":273,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9edf38ab58604f30ba0cfa0fe36964ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1227,
                  "y":431},
                "size":{
                  "width":273,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u55.png"}},
{
          "id":"cae6cb6b4c324ed59227dd824f78521b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1360,
              "y":146},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2074874f6b5d487daf2dc981cfeeaf5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1360,
                  "y":146},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0914c44b8c44071bd7dd1e634ebb3c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1285,
              "y":93},
            "size":{
              "width":217,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd241c49b88c4b8882f13f5f7d50071c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1285,
                  "y":93},
                "size":{
                  "width":217,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u59.png"}},
{
          "id":"44eddf3dd0114b6cb86e572b22d3bd36",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1502,
              "y":106},
            "size":{
              "width":108,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/自我诊断/u61_end.png",
            "line~":"images/自我诊断/u61_line.png"}},
{
          "id":"d00a79ab5cbc496db23e73c28938d90c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1506,
              "y":95},
            "size":{
              "width":92,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8470f373665e4046aa3bcd5100c172f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1506,
                  "y":95},
                "size":{
                  "width":92,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08676b52045542f3918b61f98083e88a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1654,
              "y":70},
            "size":{
              "width":169,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42fe1670807843c1bc777a2143f183a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1654,
                  "y":70},
                "size":{
                  "width":169,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u64.png"}},
{
          "id":"df4d4df6b52147fda8915996b220fa8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":173,
              "y":25},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"431dc941cab34fcb8fb79129e191cf66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":25},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23516538b61c4c6dbf971d26c4553ad3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":476,
              "y":673},
            "size":{
              "width":278,
              "height":455},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f2909032a3a4ba2b488a67f8783e24e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":476,
                  "y":673},
                "size":{
                  "width":278,
                  "height":455},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u0.png"}},
{
          "id":"c551d3818be04b94aa7003ff39e72d7d",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":300},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8cf15a455c4444fa1c449cf4be37859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":300},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}]},
{
          "id":"3f75411099b84f3ca0a8357c95862fbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1460,
              "y":362},
            "size":{
              "width":42,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eea232214bb0482f8005bc1d171c0f0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1460,
                  "y":362},
                "size":{
                  "width":42,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u72.png"}},
{
          "id":"5d068bafa38b4d5f9b27f68246d30c1e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":676,
              "y":261},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"656534a469544bc7ad255d5360c9b7aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":676,
                  "y":261},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}]},
{
          "id":"93ca9c0a6ebc4cec8707bf26cc262ffc",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1086,
              "y":248},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4164ab628220469bb376e9f2cd0a07df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1086,
                  "y":248},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}]},
{
          "id":"f01837f95a9b4cd1a591a7e5eece8ac1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":556,
              "y":634},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5997217d26c9465ab2547c11e5f54058",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":634},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9561240db3894b75a191c6c965758fd3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":556},
            "size":{
              "width":671,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/自我诊断/u80_line.png"}},
{
          "id":"7f1e41ea516049e6ac7f36d68db5695a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":700},
            "size":{
              "width":193,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a509c4ecbdc48929595a104ffbe1e27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":700},
                "size":{
                  "width":193,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e465f24f4c94d3c993b97641423ef08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":483,
              "y":738},
            "size":{
              "width":264,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"260d4e19fce84a2fb296d11afb36fe39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":483,
                  "y":738},
                "size":{
                  "width":264,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u83.png"}},
{
          "id":"7b7b5288dc0b4c15b7dd56fb859d12a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":847},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3ff24b077614819bd1345f208a6bddd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":847},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e45ddba402614ff3b2b2e899d8ed2214",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":483,
              "y":875},
            "size":{
              "width":264,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef8ec87e03a544ca9c7c11053d5de267",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":483,
                  "y":875},
                "size":{
                  "width":264,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u83.png"}},
{
          "id":"61dc434d08074a8a827eef77e5d4afd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":738},
            "size":{
              "width":294,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"880449cbce3e41d891d4b867bf5f5c7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":738},
                "size":{
                  "width":294,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d41dec59fde452eb6cad4bb47933b9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":884},
            "size":{
              "width":294,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f6d035ef7f54bf9a1cb1bffe056e757",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":884},
                "size":{
                  "width":294,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"413ba9ae537d42ef88df9c74b1dc71ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":992,
              "y":673},
            "size":{
              "width":238,
              "height":649}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aeb351ae74f45428a3d1d5e86d9d7e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":992,
                  "y":673},
                "size":{
                  "width":238,
                  "height":649}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u93.png"}},
{
          "id":"c99ac22a0ac3453eb898d625bee776fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1049,
              "y":639},
            "size":{
              "width":122,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9459558616084cddba079014a31282cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1049,
                  "y":639},
                "size":{
                  "width":122,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea3aad65d9bb4187a328338d5ac82a6b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":483,
              "y":949},
            "size":{
              "width":264,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5699f88a1ed94acc92ad535534090839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":483,
                  "y":949},
                "size":{
                  "width":264,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u83.png"}},
{
          "id":"af1393ddc59c443d83682dc98bba0057",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":477,
              "y":32},
            "size":{
              "width":323,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fc9a247e3c24503b8caae9fdc3170e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":477,
                  "y":32},
                "size":{
                  "width":323,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7dfb529057842a6a4d97d566da22ac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":496,
              "y":676},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed9f8ea503474e0aaf133a33336975a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":496,
                  "y":676},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0947bfac6e3b4d48b990f5392e2133bb":{
      "scriptId":"u0"},
    "31c8ddab648d444dabbd16b281db4232":{
      "scriptId":"u1"},
    "bd5566a029ec492b9ff6066697c81479":{
      "scriptId":"u2"},
    "b7811b4592954948a5061e25083df7ac":{
      "scriptId":"u3"},
    "59682601e90b41c3baf09cf28d3ea3a7":{
      "scriptId":"u4"},
    "c36f9da3b23e44598100aa4b46aa502a":{
      "scriptId":"u5"},
    "5555b80bbd3a4c94bf1e122aa926e4ca":{
      "scriptId":"u6"},
    "cf12d9df6e3d462f85d0596ef7cb2e01":{
      "scriptId":"u7"},
    "4ceb6fa67ade4b6798c2c83bac1d8ba6":{
      "scriptId":"u8"},
    "6f821c2c1d134e258615123c56d11f6e":{
      "scriptId":"u9"},
    "b0164c55d0c8406a853986a280b67fce":{
      "scriptId":"u10"},
    "35a4e4717e2949949830ca6f9668e979":{
      "scriptId":"u11"},
    "99392e7441204126a6331dd7529848b6":{
      "scriptId":"u12"},
    "bc9a22b013f74fc5a03ab692ed5486fb":{
      "scriptId":"u13"},
    "e576823d17e44f6b8990d97879a98f80":{
      "scriptId":"u14"},
    "692b6c531b84492485ee4d4bac858e65":{
      "scriptId":"u15"},
    "2685895a9d2b478893c9007b07d07ef2":{
      "scriptId":"u16"},
    "70761e01f560429a9bfb7b22c5582918":{
      "scriptId":"u17"},
    "072e8a85efaa4bb1828750014856c712":{
      "scriptId":"u18"},
    "6d872e0a01ca4cbd81f52ee741bbf7c7":{
      "scriptId":"u19"},
    "c2ec23b082834dbfbb1baf6fe5c37a5b":{
      "scriptId":"u20"},
    "5653a57cfa7f474892ca4f4b6a87fea9":{
      "scriptId":"u21"},
    "4c90cd87f5774ac2897c1421f70ec615":{
      "scriptId":"u22"},
    "5ccff76863904db28a22da3433041d94":{
      "scriptId":"u23"},
    "db3e2ea70e7c44cc978611b20e153d8e":{
      "scriptId":"u24"},
    "b4f0eee668044e0f88741645d354f696":{
      "scriptId":"u25"},
    "b4c0ec784b3546bcb7873407cf480d1c":{
      "scriptId":"u26"},
    "2372ef2067ad4bc6b6a27a44169fefde":{
      "scriptId":"u27"},
    "0de89fec292e4c989578132966973911":{
      "scriptId":"u28"},
    "a18c9db504494d9b9858761c3c77f390":{
      "scriptId":"u29"},
    "2b4724118b5e4fa1ba732832df15a1ee":{
      "scriptId":"u30"},
    "3bf7e663dd1e4a6eb1b2b71d86b87cc6":{
      "scriptId":"u31"},
    "662920a9f02442458960b7bbe41fb299":{
      "scriptId":"u32"},
    "7600d7181aef4e3f9cdae76520874d35":{
      "scriptId":"u33"},
    "76af810d5b264f3f9d415eda10f8386d":{
      "scriptId":"u34"},
    "c50f4232b6bc40f89ffdf929a66165c6":{
      "scriptId":"u35"},
    "654bba6de4b54626aa19f5fb4ebf824d":{
      "scriptId":"u36"},
    "4fb5bb294b1244088b090ac2d8face05":{
      "scriptId":"u37"},
    "65b55bd9e1714f7ab734b962267078c5":{
      "scriptId":"u38"},
    "56b4905fa9aa413a9beff08f7d1eb9be":{
      "scriptId":"u39"},
    "679919d7fd604655818543c5435ef7d1":{
      "scriptId":"u40"},
    "c732db8f64094863bffb19b5d725738c":{
      "scriptId":"u41"},
    "956bec501cbc45858f5934cb431208cc":{
      "scriptId":"u42"},
    "347ad237e12047fe9bb102c948913292":{
      "scriptId":"u43"},
    "a6bccc05c56144e5a39c5a9457ca8c73":{
      "scriptId":"u44"},
    "50658236d226435cbd3a624b636da585":{
      "scriptId":"u45"},
    "1441c46f00fa410d802c43ad09edfbdf":{
      "scriptId":"u46"},
    "35bea99a0a284a80bd9b6f3247be177a":{
      "scriptId":"u47"},
    "45c93d267f8e4e3eb14c105f1c822273":{
      "scriptId":"u48"},
    "abd3605c249948e4862430339c3bec9b":{
      "scriptId":"u49"},
    "e517dd89f410462a837e6e7ffaebcbec":{
      "scriptId":"u50"},
    "17ea015f6ffb4e27bfdc4f1e5f891641":{
      "scriptId":"u51"},
    "35e0cd993db5462491c34f50b3d1c44d":{
      "scriptId":"u52"},
    "078ac9217652493f9a401daece837ca1":{
      "scriptId":"u53"},
    "0f699f01b413454093390970d65e6d83":{
      "scriptId":"u54"},
    "56c6159b4b084b278256fc82f3509f40":{
      "scriptId":"u55"},
    "9edf38ab58604f30ba0cfa0fe36964ca":{
      "scriptId":"u56"},
    "cae6cb6b4c324ed59227dd824f78521b":{
      "scriptId":"u57"},
    "2074874f6b5d487daf2dc981cfeeaf5e":{
      "scriptId":"u58"},
    "d0914c44b8c44071bd7dd1e634ebb3c3":{
      "scriptId":"u59"},
    "cd241c49b88c4b8882f13f5f7d50071c":{
      "scriptId":"u60"},
    "44eddf3dd0114b6cb86e572b22d3bd36":{
      "scriptId":"u61"},
    "d00a79ab5cbc496db23e73c28938d90c":{
      "scriptId":"u62"},
    "8470f373665e4046aa3bcd5100c172f6":{
      "scriptId":"u63"},
    "08676b52045542f3918b61f98083e88a":{
      "scriptId":"u64"},
    "42fe1670807843c1bc777a2143f183a4":{
      "scriptId":"u65"},
    "df4d4df6b52147fda8915996b220fa8f":{
      "scriptId":"u66"},
    "431dc941cab34fcb8fb79129e191cf66":{
      "scriptId":"u67"},
    "23516538b61c4c6dbf971d26c4553ad3":{
      "scriptId":"u68"},
    "7f2909032a3a4ba2b488a67f8783e24e":{
      "scriptId":"u69"},
    "c551d3818be04b94aa7003ff39e72d7d":{
      "scriptId":"u70"},
    "e8cf15a455c4444fa1c449cf4be37859":{
      "scriptId":"u71"},
    "3f75411099b84f3ca0a8357c95862fbd":{
      "scriptId":"u72"},
    "eea232214bb0482f8005bc1d171c0f0f":{
      "scriptId":"u73"},
    "5d068bafa38b4d5f9b27f68246d30c1e":{
      "scriptId":"u74"},
    "656534a469544bc7ad255d5360c9b7aa":{
      "scriptId":"u75"},
    "93ca9c0a6ebc4cec8707bf26cc262ffc":{
      "scriptId":"u76"},
    "4164ab628220469bb376e9f2cd0a07df":{
      "scriptId":"u77"},
    "f01837f95a9b4cd1a591a7e5eece8ac1":{
      "scriptId":"u78"},
    "5997217d26c9465ab2547c11e5f54058":{
      "scriptId":"u79"},
    "9561240db3894b75a191c6c965758fd3":{
      "scriptId":"u80"},
    "7f1e41ea516049e6ac7f36d68db5695a":{
      "scriptId":"u81"},
    "2a509c4ecbdc48929595a104ffbe1e27":{
      "scriptId":"u82"},
    "3e465f24f4c94d3c993b97641423ef08":{
      "scriptId":"u83"},
    "260d4e19fce84a2fb296d11afb36fe39":{
      "scriptId":"u84"},
    "7b7b5288dc0b4c15b7dd56fb859d12a0":{
      "scriptId":"u85"},
    "c3ff24b077614819bd1345f208a6bddd":{
      "scriptId":"u86"},
    "e45ddba402614ff3b2b2e899d8ed2214":{
      "scriptId":"u87"},
    "ef8ec87e03a544ca9c7c11053d5de267":{
      "scriptId":"u88"},
    "61dc434d08074a8a827eef77e5d4afd2":{
      "scriptId":"u89"},
    "880449cbce3e41d891d4b867bf5f5c7a":{
      "scriptId":"u90"},
    "2d41dec59fde452eb6cad4bb47933b9b":{
      "scriptId":"u91"},
    "6f6d035ef7f54bf9a1cb1bffe056e757":{
      "scriptId":"u92"},
    "413ba9ae537d42ef88df9c74b1dc71ad":{
      "scriptId":"u93"},
    "7aeb351ae74f45428a3d1d5e86d9d7e9":{
      "scriptId":"u94"},
    "c99ac22a0ac3453eb898d625bee776fd":{
      "scriptId":"u95"},
    "9459558616084cddba079014a31282cc":{
      "scriptId":"u96"},
    "ea3aad65d9bb4187a328338d5ac82a6b":{
      "scriptId":"u97"},
    "5699f88a1ed94acc92ad535534090839":{
      "scriptId":"u98"},
    "af1393ddc59c443d83682dc98bba0057":{
      "scriptId":"u99"},
    "0fc9a247e3c24503b8caae9fdc3170e2":{
      "scriptId":"u100"},
    "d7dfb529057842a6a4d97d566da22ac9":{
      "scriptId":"u101"},
    "ed9f8ea503474e0aaf133a33336975a3":{
      "scriptId":"u102"}}});