$axure.loadCurrentPage({
  "url":"首页动画提醒.html",
  "generationDate":new Date(1481109575463.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ba327abbcced40e09a097c1a1fb2e5f3",
    "type":"Axure:Page",
    "name":"首页动画提醒",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f8b6a57ea7f442a1853b47b069db1894",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":610},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9077f279b7844868aa1616342630a8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":610},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"911d20efa92c405993c0100d3c256ea4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":968},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d351c0a18ac14b3494dd023022c9484d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":968},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd1c2c2b0716481baee268dc64885714",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":60,
              "y":1056},
            "size":{
              "width":209,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87c7ecd5bb454d3a84b86298b773b539",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":1056},
                "size":{
                  "width":209,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57404d8436ba435ba09f5d0ef9c2f208",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":60,
              "y":659},
            "size":{
              "width":284,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7c7d99baa6468fb6e8ce1028c538d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":60,
                  "y":659},
                "size":{
                  "width":284,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb3e919dc8d242668431c2fb9dac71c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":60,
              "y":1022},
            "size":{
              "width":324,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dc659860f0243d9a050d990a3bea10b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":60,
                  "y":1022},
                "size":{
                  "width":324,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b7f8bcb911e409c91b9b99004fdaa01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":60,
              "y":694},
            "size":{
              "width":340,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e57dcc82695a4ac7804d83f8cf81cded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":694},
                "size":{
                  "width":340,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c63d36a17c4c432ab21463f1dfa02d58",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":402,
              "y":659},
            "size":{
              "width":260,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97dfc9ad3e2c41e1adf4891673d2affd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":402,
                  "y":659},
                "size":{
                  "width":260,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06411de9e8104e7f9f3820afee54f648",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":729,
              "y":659},
            "size":{
              "width":274,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04f467cf1d1c44bfb32a7a8d6cf2137f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":729,
                  "y":659},
                "size":{
                  "width":274,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abb27e46c73c4f5f8cb08a5ecf67f67c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":402,
              "y":694},
            "size":{
              "width":278,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4557a315a043049efeee8594ac537a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":402,
                  "y":694},
                "size":{
                  "width":278,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"736026634b004bc5ada1455606bf4e02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":729,
              "y":694},
            "size":{
              "width":340,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5798d7f4862e4fddb39e3bc080dcbdd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":729,
                  "y":694},
                "size":{
                  "width":340,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b708cb3adeb4d018c8dc450c53c07e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":60,
              "y":788},
            "size":{
              "width":201,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d59c8eaf1bb4332a67303cbfe9ff9f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":60,
                  "y":788},
                "size":{
                  "width":201,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbb2acb88d7648188e46622b7e69606d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":402,
              "y":788},
            "size":{
              "width":280,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbf7ad45fa47451bb9cb11d9f282bb0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":402,
                  "y":788},
                "size":{
                  "width":280,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61b272d1986f4577acf504a0cbef0754",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":729,
              "y":788},
            "size":{
              "width":198,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe65c2dc8fcb4a3a8aa34cdb64509bc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":729,
                  "y":788},
                "size":{
                  "width":198,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ed80e7785c94b7ebb9c9bddfc00145f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":60,
              "y":822},
            "size":{
              "width":340,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a78815b076b545aab046de812270e403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":822},
                "size":{
                  "width":340,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e209c6f90a4d41caa481cbf767d2108e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":60,
              "y":861},
            "size":{
              "width":340,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"067b375aa1bd48c481d414f6180747fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":861},
                "size":{
                  "width":340,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"922ba3e4082b4f208da856251962eaac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":400,
              "y":822},
            "size":{
              "width":340,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2082e0d03b6444888775c29a335ce8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":400,
                  "y":822},
                "size":{
                  "width":340,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e228798f7d844bb8a0c3a5534554d34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":729,
              "y":822},
            "size":{
              "width":340,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4281a24a663e4e59bb52bcfabf8b4745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":729,
                  "y":822},
                "size":{
                  "width":340,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54cf30354d6e4b6f875de212546577c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":442,
              "y":1056},
            "size":{
              "width":413,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d80e94b4647c408eb862ce42cebc4290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":442,
                  "y":1056},
                "size":{
                  "width":413,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da35843ce07748579386d9851953aac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":60,
              "y":1076},
            "size":{
              "width":113,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c216bb401464d269bd7f8c7d8afdfd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":1076},
                "size":{
                  "width":113,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32038851114248e7bceeb63d983fb151",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":60,
              "y":1096},
            "size":{
              "width":85,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"670defa6111d49db98bfe82e2b92f4f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":1096},
                "size":{
                  "width":85,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3077140bc1a4d4ea44715e3f454631d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":442,
              "y":1022},
            "size":{
              "width":480,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e8d5132e70148c9b93a78600ec5ff18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":442,
                  "y":1022},
                "size":{
                  "width":480,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b144310de4a4c7ca1aafd991c425c38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":180,
              "y":617},
            "size":{
              "width":340,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e44278f40adb4891b8c8e5660c52ad9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":617},
                "size":{
                  "width":340,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5372e8fc3254871bb053b5a2136543e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":22},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86334c8f062b4cbbaf3479725f4edc5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":22},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e8830dca6524e7c8d85d6152ce9ec60",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":272,
              "height":481}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eb7b60e61614e5dad44a5ae0e3e52a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":272,
                  "height":481}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动画提醒/u46.jpg"}},
{
          "id":"00eebd2bbe2a44ad93c734b0fb4054b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":80,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0eee11b120f5424b8e651886ae1e5949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":80,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动画提醒/u48.png"}},
{
          "id":"f3d91eb2e61d4ca9aac30f840aeacc67",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":60},
            "size":{
              "width":271,
              "height":481}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0daad21eda74767bfba3eeebe2513d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":60},
                "size":{
                  "width":271,
                  "height":481}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u20.jpg"}},
{
          "id":"c84363510fb044bf8169394fd475d4a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":93},
            "size":{
              "width":266,
              "height":206}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c219f933780040108abbd69979ca6825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":374,
                  "y":93},
                "size":{
                  "width":266,
                  "height":206}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u22.png"}},
{
          "id":"bd39093e0a1c499381d1566e83f1a2a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":411},
            "size":{
              "width":149,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4dd5db3e53846adaa9d836299d382d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":411},
                "size":{
                  "width":149,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u24.png"}},
{
          "id":"03232cf91c2e4e6fa92f7ca6410990fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":462,
              "y":422},
            "size":{
              "width":93,
              "height":93},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cb126dafd764b779b74dfc68ddb6921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":462,
                  "y":422},
                "size":{
                  "width":93,
                  "height":93},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动画提醒/u56.png"}},
{
          "id":"eb9df04cfb934269907705de824b7998",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":381,
              "y":114},
            "size":{
              "width":249,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"911548cb560e47a194ce1a63f9f529d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":381,
                  "y":114},
                "size":{
                  "width":249,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fe7c8bedba744a08438f4f67142cb7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":430,
              "y":133},
            "size":{
              "width":210,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"948e1f13ef6c4c8e8a8804998c1e5bac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":430,
                  "y":133},
                "size":{
                  "width":210,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7907a59ea77344b49bc279f715452ee5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":162},
            "size":{
              "width":252,
              "height":75},
            "cornerRadiusTopLeft":"13"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c0451ce9f0e4d468c3a07a41fde68e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":162},
                "size":{
                  "width":252,
                  "height":75},
                "cornerRadiusTopLeft":"13"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动画提醒/u62.png"}},
{
          "id":"b8e411d3bc9f48d69eb9f052d621c156",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":60},
            "size":{
              "width":271,
              "height":481}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"131af204884a4057a1d74b8dd278513c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":60},
                "size":{
                  "width":271,
                  "height":481}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动画提醒/u64.jpg"}},
{
          "id":"10657ae614934f6ea9c8a68c3bfad7a8",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":510},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c53c2d0f58e94a4e95f9443cf0385ca8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":510},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}]},
{
          "id":"7e20e387b73f4d48afa1bc5542c5b681",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":555,
              "y":466},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0786d18cf78488491e6c3a605ec5aeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":555,
                  "y":466},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}]},
{
          "id":"4dbc6e3633b642178961cc49e3c72609",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":698,
              "y":93},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df822308032848a58980e8f7dac3ef4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698,
                  "y":93},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f8b6a57ea7f442a1853b47b069db1894":{
      "scriptId":"u0"},
    "b9077f279b7844868aa1616342630a8d":{
      "scriptId":"u1"},
    "911d20efa92c405993c0100d3c256ea4":{
      "scriptId":"u2"},
    "d351c0a18ac14b3494dd023022c9484d":{
      "scriptId":"u3"},
    "cd1c2c2b0716481baee268dc64885714":{
      "scriptId":"u4"},
    "87c7ecd5bb454d3a84b86298b773b539":{
      "scriptId":"u5"},
    "57404d8436ba435ba09f5d0ef9c2f208":{
      "scriptId":"u6"},
    "9f7c7d99baa6468fb6e8ce1028c538d5":{
      "scriptId":"u7"},
    "bb3e919dc8d242668431c2fb9dac71c1":{
      "scriptId":"u8"},
    "9dc659860f0243d9a050d990a3bea10b":{
      "scriptId":"u9"},
    "6b7f8bcb911e409c91b9b99004fdaa01":{
      "scriptId":"u10"},
    "e57dcc82695a4ac7804d83f8cf81cded":{
      "scriptId":"u11"},
    "c63d36a17c4c432ab21463f1dfa02d58":{
      "scriptId":"u12"},
    "97dfc9ad3e2c41e1adf4891673d2affd":{
      "scriptId":"u13"},
    "06411de9e8104e7f9f3820afee54f648":{
      "scriptId":"u14"},
    "04f467cf1d1c44bfb32a7a8d6cf2137f":{
      "scriptId":"u15"},
    "abb27e46c73c4f5f8cb08a5ecf67f67c":{
      "scriptId":"u16"},
    "1a4557a315a043049efeee8594ac537a":{
      "scriptId":"u17"},
    "736026634b004bc5ada1455606bf4e02":{
      "scriptId":"u18"},
    "5798d7f4862e4fddb39e3bc080dcbdd5":{
      "scriptId":"u19"},
    "3b708cb3adeb4d018c8dc450c53c07e7":{
      "scriptId":"u20"},
    "6d59c8eaf1bb4332a67303cbfe9ff9f7":{
      "scriptId":"u21"},
    "bbb2acb88d7648188e46622b7e69606d":{
      "scriptId":"u22"},
    "dbf7ad45fa47451bb9cb11d9f282bb0a":{
      "scriptId":"u23"},
    "61b272d1986f4577acf504a0cbef0754":{
      "scriptId":"u24"},
    "fe65c2dc8fcb4a3a8aa34cdb64509bc6":{
      "scriptId":"u25"},
    "7ed80e7785c94b7ebb9c9bddfc00145f":{
      "scriptId":"u26"},
    "a78815b076b545aab046de812270e403":{
      "scriptId":"u27"},
    "e209c6f90a4d41caa481cbf767d2108e":{
      "scriptId":"u28"},
    "067b375aa1bd48c481d414f6180747fa":{
      "scriptId":"u29"},
    "922ba3e4082b4f208da856251962eaac":{
      "scriptId":"u30"},
    "d2082e0d03b6444888775c29a335ce8b":{
      "scriptId":"u31"},
    "1e228798f7d844bb8a0c3a5534554d34":{
      "scriptId":"u32"},
    "4281a24a663e4e59bb52bcfabf8b4745":{
      "scriptId":"u33"},
    "54cf30354d6e4b6f875de212546577c7":{
      "scriptId":"u34"},
    "d80e94b4647c408eb862ce42cebc4290":{
      "scriptId":"u35"},
    "da35843ce07748579386d9851953aac9":{
      "scriptId":"u36"},
    "7c216bb401464d269bd7f8c7d8afdfd0":{
      "scriptId":"u37"},
    "32038851114248e7bceeb63d983fb151":{
      "scriptId":"u38"},
    "670defa6111d49db98bfe82e2b92f4f3":{
      "scriptId":"u39"},
    "c3077140bc1a4d4ea44715e3f454631d":{
      "scriptId":"u40"},
    "4e8d5132e70148c9b93a78600ec5ff18":{
      "scriptId":"u41"},
    "1b144310de4a4c7ca1aafd991c425c38":{
      "scriptId":"u42"},
    "e44278f40adb4891b8c8e5660c52ad9f":{
      "scriptId":"u43"},
    "b5372e8fc3254871bb053b5a2136543e":{
      "scriptId":"u44"},
    "86334c8f062b4cbbaf3479725f4edc5b":{
      "scriptId":"u45"},
    "3e8830dca6524e7c8d85d6152ce9ec60":{
      "scriptId":"u46"},
    "3eb7b60e61614e5dad44a5ae0e3e52a4":{
      "scriptId":"u47"},
    "00eebd2bbe2a44ad93c734b0fb4054b3":{
      "scriptId":"u48"},
    "0eee11b120f5424b8e651886ae1e5949":{
      "scriptId":"u49"},
    "f3d91eb2e61d4ca9aac30f840aeacc67":{
      "scriptId":"u50"},
    "e0daad21eda74767bfba3eeebe2513d2":{
      "scriptId":"u51"},
    "c84363510fb044bf8169394fd475d4a4":{
      "scriptId":"u52"},
    "c219f933780040108abbd69979ca6825":{
      "scriptId":"u53"},
    "bd39093e0a1c499381d1566e83f1a2a9":{
      "scriptId":"u54"},
    "f4dd5db3e53846adaa9d836299d382d1":{
      "scriptId":"u55"},
    "03232cf91c2e4e6fa92f7ca6410990fd":{
      "scriptId":"u56"},
    "3cb126dafd764b779b74dfc68ddb6921":{
      "scriptId":"u57"},
    "eb9df04cfb934269907705de824b7998":{
      "scriptId":"u58"},
    "911548cb560e47a194ce1a63f9f529d5":{
      "scriptId":"u59"},
    "0fe7c8bedba744a08438f4f67142cb7f":{
      "scriptId":"u60"},
    "948e1f13ef6c4c8e8a8804998c1e5bac":{
      "scriptId":"u61"},
    "7907a59ea77344b49bc279f715452ee5":{
      "scriptId":"u62"},
    "2c0451ce9f0e4d468c3a07a41fde68e2":{
      "scriptId":"u63"},
    "b8e411d3bc9f48d69eb9f052d621c156":{
      "scriptId":"u64"},
    "131af204884a4057a1d74b8dd278513c":{
      "scriptId":"u65"},
    "10657ae614934f6ea9c8a68c3bfad7a8":{
      "scriptId":"u66"},
    "c53c2d0f58e94a4e95f9443cf0385ca8":{
      "scriptId":"u67"},
    "7e20e387b73f4d48afa1bc5542c5b681":{
      "scriptId":"u68"},
    "f0786d18cf78488491e6c3a605ec5aeb":{
      "scriptId":"u69"},
    "4dbc6e3633b642178961cc49e3c72609":{
      "scriptId":"u70"},
    "df822308032848a58980e8f7dac3ef4a":{
      "scriptId":"u71"}}});