$axure.loadCurrentPage({
  "url":"我的手机.html",
  "generationDate":new Date(1480575726684.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1fd9f007cb12410eb5f5aad63fcc1db9",
    "type":"Axure:Page",
    "name":"我的手机",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7922d3bc39da40cb8eada2c916aa1b3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":79,
              "y":50},
            "size":{
              "width":311,
              "height":770},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"23"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82cd124056e44e2887742522da9286b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":50},
                "size":{
                  "width":311,
                  "height":770},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"23"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的手机/u0.png"}},
{
          "id":"e952a74e0bf54cf3a10e20bd761fa552",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":101,
              "y":114},
            "size":{
              "width":270,
              "height":656},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c9ef9e5dcf471ca25cf945883e648e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":101,
                  "y":114},
                "size":{
                  "width":270,
                  "height":656},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的手机/u2.png"}},
{
          "id":"6089da74d89b4b7aa7e6a3c121a5cf46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":225,
              "y":79},
            "size":{
              "width":34,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"23"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dcf2631c8564ded91935629dacca434",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":225,
                  "y":79},
                "size":{
                  "width":34,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"23"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u6.png"}},
{
          "id":"293a28be7b944f5582d0f56001d2d784",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":209,
              "y":79},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"23"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11fa5ebf0cc04967a23cb3153accc0cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":209,
                  "y":79},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"23"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u8.png"}},
{
          "id":"f44d451b5c7d4fcbbed5743e5c96890a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":114},
            "size":{
              "width":270,
              "height":146},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.0980392156862745}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0eaed4218472412c93bf555c8c64d078",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":114},
                "size":{
                  "width":270,
                  "height":146},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.0980392156862745}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的手机/u8.png"}},
{
          "id":"94ded38497c843aaa975f33c58468cc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":101,
              "y":114},
            "size":{
              "width":270,
              "height":58},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae8d0c83ac584fb8946bf4b74d5061f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":101,
                  "y":114},
                "size":{
                  "width":270,
                  "height":58},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的手机/u10.png"}},
{
          "id":"ebd87ef265834a1592996fd352ef236e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":124},
            "size":{
              "width":36,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fc3c548e1944aeeb3bc88460f142702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":124},
                "size":{
                  "width":36,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的手机/u12.png"}},
{
          "id":"838eae15fa3043ba8f2b19f4ebc435a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":157,
              "y":130},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8753d265eef14addb5934e9ec37e31f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":130},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"018634c40bc041ce9a5c5b0703ae61ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":228,
              "y":134},
            "size":{
              "width":128,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c1f0ee5d17849ca9b8fb4ae94951458",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":228,
                  "y":134},
                "size":{
                  "width":128,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ba88858f9c24bc09ca6e6ad39a6e7a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":197,
              "y":202},
            "size":{
              "width":112,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"636c77a738e5437f95cc6001bb791700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":197,
                  "y":202},
                "size":{
                  "width":112,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"131291ae27bb47a3a178f6a332094811",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":290},
            "size":{
              "width":270,
              "height":170},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.0980392156862745}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c5eae0d7ee64a6bb3ca7112b6c8906a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":290},
                "size":{
                  "width":270,
                  "height":170},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.0980392156862745}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的手机/u20.png"}},
{
          "id":"991ac08df6a146c6ab0f5048f02c612c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":120,
              "y":268},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fca4799f030c4948b33bc2a187ae3bad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":268},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31067ccb3a9d4571aa092ced9208a1b1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":328},
            "size":{
              "width":231,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的手机/u24_line.png"}},
{
          "id":"1ff285efd8034c5fb0f33552e21d7602",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":121,
              "y":430},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18946a5e5dd740f0bf63ee1684be828a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":430},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6b48f99d21d4cb6a86d79d0efa9dafc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":368},
            "size":{
              "width":231,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的手机/u24_line.png"}},
{
          "id":"cb6d6d98b96a4c00acd6f3431ac994c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":120,
              "y":303},
            "size":{
              "width":65,
              "height":1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"189ee015daaa423bb516cae8ea052a3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":303},
                "size":{
                  "width":65,
                  "height":1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2965c5d2572c4a72bd618e9c9e0898b1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":411},
            "size":{
              "width":231,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的手机/u24_line.png"}},
{
          "id":"dc6dfca57e6840b188a2d3a111b26ec6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":120,
              "y":343},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f7de8cef3d748edbcc53e6980d787c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":343},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14ff715d86ed408e89fba14172c6c2cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":120,
              "y":385},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eafe86f4eb0c401bb4407f816f808e48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":385},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b659da47b2b461d816c581f13509082",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":489},
            "size":{
              "width":270,
              "height":84},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.0980392156862745}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dec435d326414fe7a7679879fb0f44ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":489},
                "size":{
                  "width":270,
                  "height":84},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.0980392156862745}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的手机/u35.png"}},
{
          "id":"09c78a0bfc9a4e36b3db97c490d5e4ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":121,
              "y":467},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6a9f5a72a274eddaf089d6b883f223e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":467},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"deeb073339a548b59fc2c3b8541ae541",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":527},
            "size":{
              "width":231,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的手机/u24_line.png"}},
{
          "id":"3df589b7b05a473bb75192779e402cd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":121,
              "y":501},
            "size":{
              "width":44,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e904d50ab5c0451ca4ee1377c474c6e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":501},
                "size":{
                  "width":44,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79aed1c57a2b4d768fc4079a5e8c2ace",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":121,
              "y":542},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b5f7c70637f4cc9a5af3d98038451bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":542},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"699cdc3eb658480ea22ba1a1164eb061",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":603},
            "size":{
              "width":270,
              "height":139},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":false,
              "offsetX":0,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.0980392156862745}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c5206acf3eb48d2b5658acef79b95ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":603},
                "size":{
                  "width":270,
                  "height":139},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.0980392156862745}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的手机/u44.png"}},
{
          "id":"0797dab5e2da4eff82fc7c540150ba10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":121,
              "y":581},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8390669e46e3486a9d52b8325a9e47c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":581},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"620fb6cf47f343039b2137eaa88a271f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":641},
            "size":{
              "width":231,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的手机/u24_line.png"}},
{
          "id":"868def308b0f4aa5b464ef8b843858b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":121,
              "y":615},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e22b6811c6104ccc97bd3d0a84ffb41b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":615},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8dd4fbf98114f0ba47afa8a44a1f304",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":687},
            "size":{
              "width":231,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的手机/u24_line.png"}},
{
          "id":"512e4a474af346f58c3087125949f17b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":121,
              "y":661},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5407423fc3bc42a0a144067dd7487743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":661},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afa6a8ea369f42b3b05bb1aa9794db22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":121,
              "y":707},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99b35e306d354bb8a0a8fd5d66e106d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":707},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b5a5a8a932a4548b30ada099ea168fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":121,
              "y":748},
            "size":{
              "width":96,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"379a8c9d86684e0cbc57525858ea2b69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":748},
                "size":{
                  "width":96,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abc87b135aff491f80c5ccf2f03d8e5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF66},
            "location":{
              "x":121,
              "y":190},
            "size":{
              "width":49,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"100",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aecc0b4324540409c83decd565c887e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF66},
                "location":{
                  "x":121,
                  "y":190},
                "size":{
                  "width":49,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"100",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的手机/u58.png"}},
{
          "id":"099ad9d9208542d0b3c382abc067e191",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":92},
            "size":{
              "width":200,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"138e7d8fdba5437791342b09dee62765",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":92},
                "size":{
                  "width":200,
                  "height":192}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7922d3bc39da40cb8eada2c916aa1b3a":{
      "scriptId":"u0"},
    "82cd124056e44e2887742522da9286b9":{
      "scriptId":"u1"},
    "e952a74e0bf54cf3a10e20bd761fa552":{
      "scriptId":"u2"},
    "79c9ef9e5dcf471ca25cf945883e648e":{
      "scriptId":"u3"},
    "6089da74d89b4b7aa7e6a3c121a5cf46":{
      "scriptId":"u4"},
    "4dcf2631c8564ded91935629dacca434":{
      "scriptId":"u5"},
    "293a28be7b944f5582d0f56001d2d784":{
      "scriptId":"u6"},
    "11fa5ebf0cc04967a23cb3153accc0cc":{
      "scriptId":"u7"},
    "f44d451b5c7d4fcbbed5743e5c96890a":{
      "scriptId":"u8"},
    "0eaed4218472412c93bf555c8c64d078":{
      "scriptId":"u9"},
    "94ded38497c843aaa975f33c58468cc2":{
      "scriptId":"u10"},
    "ae8d0c83ac584fb8946bf4b74d5061f2":{
      "scriptId":"u11"},
    "ebd87ef265834a1592996fd352ef236e":{
      "scriptId":"u12"},
    "2fc3c548e1944aeeb3bc88460f142702":{
      "scriptId":"u13"},
    "838eae15fa3043ba8f2b19f4ebc435a6":{
      "scriptId":"u14"},
    "8753d265eef14addb5934e9ec37e31f5":{
      "scriptId":"u15"},
    "018634c40bc041ce9a5c5b0703ae61ec":{
      "scriptId":"u16"},
    "9c1f0ee5d17849ca9b8fb4ae94951458":{
      "scriptId":"u17"},
    "8ba88858f9c24bc09ca6e6ad39a6e7a3":{
      "scriptId":"u18"},
    "636c77a738e5437f95cc6001bb791700":{
      "scriptId":"u19"},
    "131291ae27bb47a3a178f6a332094811":{
      "scriptId":"u20"},
    "1c5eae0d7ee64a6bb3ca7112b6c8906a":{
      "scriptId":"u21"},
    "991ac08df6a146c6ab0f5048f02c612c":{
      "scriptId":"u22"},
    "fca4799f030c4948b33bc2a187ae3bad":{
      "scriptId":"u23"},
    "31067ccb3a9d4571aa092ced9208a1b1":{
      "scriptId":"u24"},
    "1ff285efd8034c5fb0f33552e21d7602":{
      "scriptId":"u25"},
    "18946a5e5dd740f0bf63ee1684be828a":{
      "scriptId":"u26"},
    "d6b48f99d21d4cb6a86d79d0efa9dafc":{
      "scriptId":"u27"},
    "cb6d6d98b96a4c00acd6f3431ac994c6":{
      "scriptId":"u28"},
    "189ee015daaa423bb516cae8ea052a3f":{
      "scriptId":"u29"},
    "2965c5d2572c4a72bd618e9c9e0898b1":{
      "scriptId":"u30"},
    "dc6dfca57e6840b188a2d3a111b26ec6":{
      "scriptId":"u31"},
    "1f7de8cef3d748edbcc53e6980d787c0":{
      "scriptId":"u32"},
    "14ff715d86ed408e89fba14172c6c2cf":{
      "scriptId":"u33"},
    "eafe86f4eb0c401bb4407f816f808e48":{
      "scriptId":"u34"},
    "1b659da47b2b461d816c581f13509082":{
      "scriptId":"u35"},
    "dec435d326414fe7a7679879fb0f44ba":{
      "scriptId":"u36"},
    "09c78a0bfc9a4e36b3db97c490d5e4ca":{
      "scriptId":"u37"},
    "f6a9f5a72a274eddaf089d6b883f223e":{
      "scriptId":"u38"},
    "deeb073339a548b59fc2c3b8541ae541":{
      "scriptId":"u39"},
    "3df589b7b05a473bb75192779e402cd7":{
      "scriptId":"u40"},
    "e904d50ab5c0451ca4ee1377c474c6e4":{
      "scriptId":"u41"},
    "79aed1c57a2b4d768fc4079a5e8c2ace":{
      "scriptId":"u42"},
    "3b5f7c70637f4cc9a5af3d98038451bb":{
      "scriptId":"u43"},
    "699cdc3eb658480ea22ba1a1164eb061":{
      "scriptId":"u44"},
    "2c5206acf3eb48d2b5658acef79b95ac":{
      "scriptId":"u45"},
    "0797dab5e2da4eff82fc7c540150ba10":{
      "scriptId":"u46"},
    "8390669e46e3486a9d52b8325a9e47c2":{
      "scriptId":"u47"},
    "620fb6cf47f343039b2137eaa88a271f":{
      "scriptId":"u48"},
    "868def308b0f4aa5b464ef8b843858b1":{
      "scriptId":"u49"},
    "e22b6811c6104ccc97bd3d0a84ffb41b":{
      "scriptId":"u50"},
    "f8dd4fbf98114f0ba47afa8a44a1f304":{
      "scriptId":"u51"},
    "512e4a474af346f58c3087125949f17b":{
      "scriptId":"u52"},
    "5407423fc3bc42a0a144067dd7487743":{
      "scriptId":"u53"},
    "afa6a8ea369f42b3b05bb1aa9794db22":{
      "scriptId":"u54"},
    "99b35e306d354bb8a0a8fd5d66e106d8":{
      "scriptId":"u55"},
    "5b5a5a8a932a4548b30ada099ea168fc":{
      "scriptId":"u56"},
    "379a8c9d86684e0cbc57525858ea2b69":{
      "scriptId":"u57"},
    "abc87b135aff491f80c5ccf2f03d8e5b":{
      "scriptId":"u58"},
    "3aecc0b4324540409c83decd565c887e":{
      "scriptId":"u59"},
    "099ad9d9208542d0b3c382abc067e191":{
      "scriptId":"u60"},
    "138e7d8fdba5437791342b09dee62765":{
      "scriptId":"u61"}}});