$axure.loadCurrentPage({
  "url":"首页动态条.html",
  "generationDate":new Date(1481642347703.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ce4694f6bafa4b17912fe9dc89fbc713",
    "type":"Axure:Page",
    "name":"首页动态条",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8caf2451ccc54d6e8b9d599d706d81c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":844},
            "size":{
              "width":279,
              "height":68},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be74241e1424df58ff5df66113c6d07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":844},
                "size":{
                  "width":279,
                  "height":68},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页动态条/u0.png"}},
{
          "id":"4396efa33e814956babe5b919ffe4223",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":177,
              "y":857},
            "size":{
              "width":149,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de9859debf1c44d8a0d03616f009c7cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":177,
                  "y":857},
                "size":{
                  "width":149,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"199990b2295c4ca0899c696c688a9fe1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":851},
            "size":{
              "width":10,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/中间页交互/u66_line.png"}},
{
          "id":"3b32dc8a113e4f2e974d5d7565e0522e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":177,
              "y":879},
            "size":{
              "width":149,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5a700b2b7374e5884b705a1b922cc5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":177,
                  "y":879},
                "size":{
                  "width":149,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"769e9ab0bf0c493182a97d1de5637c02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":844},
            "size":{
              "width":183,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe15f05a165e4f59b70612c5b488b1a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":844},
                "size":{
                  "width":183,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"276beda77e264b1f800a9ab0ba454ae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":622,
              "y":844},
            "size":{
              "width":172,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3819d4ebaef491e9c5a73f1b682c7d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":622,
                  "y":844},
                "size":{
                  "width":172,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bea449b0785a44ba93a2abb4d9f4f504",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":883},
            "size":{
              "width":259,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3707efb66d8f4c1d978f706f7883778e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":883},
                "size":{
                  "width":259,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7714799355244388995eddb715527a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":956},
            "size":{
              "width":213,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c5c4e5b6434656b1552b7859a4d77d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":956},
                "size":{
                  "width":213,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a24d3987eb134d76909bda7c4c48b04c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":43},
            "size":{
              "width":73,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"656c4923fd234328828cb73e27f7aed8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":43},
                "size":{
                  "width":73,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6df9a8512b5b456ca6b2f98ea510a7bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":467},
            "size":{
              "width":217,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1408294ebbd433f93fc9ed4e37287f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":467},
                "size":{
                  "width":217,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4594108bcb734ab8be539949496b45f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":81},
            "size":{
              "width":279,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af10500baba452fa3312bf87f2bf3e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":81},
                "size":{
                  "width":279,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u26.png"}},
{
          "id":"d186c1dd085644149643233e89a02d3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":167,
              "y":91},
            "size":{
              "width":159,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13d93ed8596148b384e27bd5f1f094c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":167,
                  "y":91},
                "size":{
                  "width":159,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28cd455ce772410f833d96d9464cd318",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Negreta', 'Agency FB'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":80,
              "y":87},
            "size":{
              "width":49,
              "height":45},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81ee9f53ab8d4fedb9a1c06f1e318444",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Negreta', 'Agency FB'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":80,
                  "y":87},
                "size":{
                  "width":49,
                  "height":45},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u30.png"}},
{
          "id":"1a628775d7684390ae155ce07c6b4371",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":87},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录流程/u32_line.png"}},
{
          "id":"a10d387ded024150a775b2a0f330ba06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":103},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a096c5cd9d90405f89963c1d428b0f8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":103},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0460795265044ba7bc134e09f08a7b6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":222},
            "size":{
              "width":217,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95edb97025ee44cf9a1004f6f2f39fd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":222},
                "size":{
                  "width":217,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7793b4e07924f9db00a134fafa7802b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":260},
            "size":{
              "width":279,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"636fc7369bf1483485e75f8c23f63fd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":260},
                "size":{
                  "width":279,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u26.png"}},
{
          "id":"976c9b9e8902450791b81af1a3968d0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":167,
              "y":270},
            "size":{
              "width":159,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbe348cce3af4fbd8af39ccaad1fff92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":167,
                  "y":270},
                "size":{
                  "width":159,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6b1eadaa2bb448e9e77983522e02c4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Negreta', 'Agency FB'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":80,
              "y":266},
            "size":{
              "width":49,
              "height":45},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06d5de7173a9444aa4d882ed96fd44b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Negreta', 'Agency FB'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":80,
                  "y":266},
                "size":{
                  "width":49,
                  "height":45},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u30.png"}},
{
          "id":"85c19db49e6d4c5d9079a25d6b8db737",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":266},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录流程/u32_line.png"}},
{
          "id":"8e16645c50364fdca9ab619c15b82993",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":175,
              "y":723},
            "size":{
              "width":235,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5037ef93898d436490078366a3ea4df1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":175,
                  "y":723},
                "size":{
                  "width":235,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38160e290312456a83ed8fa7d0ce8cfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":722},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f44439cf2bb04ac4ad4c3e77f8eebe38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":722},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"138254c8892547bbae9b281d97ca4ac7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":329},
            "size":{
              "width":279,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24e5e6c742374dc0a971122b0cbab8f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":329},
                "size":{
                  "width":279,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u26.png"}},
{
          "id":"056507b2f4a74636988da50067b40d30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":167,
              "y":339},
            "size":{
              "width":159,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43158369a3a94113bc572aaf7d9b383a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":167,
                  "y":339},
                "size":{
                  "width":159,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0ee2df9c8354af9b77725a88127239a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Negreta', 'Agency FB'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":80,
              "y":335},
            "size":{
              "width":49,
              "height":45},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc7efd2552034abfb817935aabd8e2b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Negreta', 'Agency FB'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":80,
                  "y":335},
                "size":{
                  "width":49,
                  "height":45},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u30.png"}},
{
          "id":"6c2f76bddf844d098f5cfdcb4f1df43c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":335},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录流程/u32_line.png"}},
{
          "id":"57c3ecd212194e258fb3fd593e499eba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":351},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"922800ee38014b3fb1e58b697a1952ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":351},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5af31a2cb22e4c5a9723b08274d1c3fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":284},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c075af05cfd4616b90c480454d5d9e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":284},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b243b0516ab420995a69b0075681bfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":520},
            "size":{
              "width":279,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f37a15f8590d46bd9443ae42d50dd4da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":520},
                "size":{
                  "width":279,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u26.png"}},
{
          "id":"2d319ac492334cb38641df1bccdc8260",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":167,
              "y":530},
            "size":{
              "width":159,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde6a55235e34b0ea6b7afa3eca841f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":167,
                  "y":530},
                "size":{
                  "width":159,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d98206103cf740238bc0e8f95d02f167",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Negreta', 'Agency FB'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":80,
              "y":526},
            "size":{
              "width":49,
              "height":45},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"802cfeef08d64a568ee27e799d8cf3fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Negreta', 'Agency FB'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":80,
                  "y":526},
                "size":{
                  "width":49,
                  "height":45},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u30.png"}},
{
          "id":"f22cea1fa36f4a23b0a63f77e4a31d39",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":526},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录流程/u32_line.png"}},
{
          "id":"c7e4d39079da44fd996bce8e875bbcad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":544},
            "size":{
              "width":222,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30c7d39cd7b54f32a4ff4e3a6f299cac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":544},
                "size":{
                  "width":222,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d50d54c3a5544b6b834bdebca818a8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":589},
            "size":{
              "width":279,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f03277f4ba8b4b5095b1089f74556ab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":589},
                "size":{
                  "width":279,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u26.png"}},
{
          "id":"79b74a0e117a4d91acf0ec879e4bf8b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":167,
              "y":599},
            "size":{
              "width":159,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5161cb4ed8542c999cb75f4562220ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":167,
                  "y":599},
                "size":{
                  "width":159,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a644f6f019d04ae7a899ae08c3a30575",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Negreta', 'Agency FB'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":80,
              "y":595},
            "size":{
              "width":49,
              "height":45},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32e3aa5b611e4ed4a079a9a59c6ddc0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Negreta', 'Agency FB'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":80,
                  "y":595},
                "size":{
                  "width":49,
                  "height":45},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u30.png"}},
{
          "id":"48d16c3f38114840a170919ffb90a916",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":595},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录流程/u32_line.png"}},
{
          "id":"c5ca6bc6d6534363b0a47c3c7ef7c36d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":611},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff6930ed6954c24a41e044e3c0f7165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":611},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7922cbc86233420eabe13138e8044561",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":760},
            "size":{
              "width":279,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfdb5edcf36d49c69c23371c35a82c5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":760},
                "size":{
                  "width":279,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u26.png"}},
{
          "id":"3cb24a1835e74857be839118625d2244",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":167,
              "y":770},
            "size":{
              "width":159,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f08e5c906d6a409dbd66b4356e7db353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":167,
                  "y":770},
                "size":{
                  "width":159,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"854eb626ddfd4a13a4bcd565fc59f3f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Negreta', 'Agency FB'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":80,
              "y":766},
            "size":{
              "width":49,
              "height":45},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"480debd1972e427f96e7ada97c71fdb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Negreta', 'Agency FB'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":80,
                  "y":766},
                "size":{
                  "width":49,
                  "height":45},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u30.png"}},
{
          "id":"993015d7b0354585937d90cd5d45e140",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":766},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录流程/u32_line.png"}},
{
          "id":"5f47b327168e4823bfe44e63a0763c3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":782},
            "size":{
              "width":222,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"318d975eff97464da69009c92a809086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":782},
                "size":{
                  "width":222,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8badd1cc029476b8da62f7f9177ab57",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Negreta', 'Agency FB'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":80,
              "y":856},
            "size":{
              "width":49,
              "height":45},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6ec5e0ef1bc4efabf7e9f70447d3f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Negreta', 'Agency FB'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":80,
                  "y":856},
                "size":{
                  "width":49,
                  "height":45},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u30.png"}},
{
          "id":"dc69d3e8938f4baaafc544738a483a1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":622,
              "y":467},
            "size":{
              "width":213,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43ef523a36e34b5a963d4abe85cc3568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":622,
                  "y":467},
                "size":{
                  "width":213,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a0558fa87564710a8cb307cce7e6727",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":854,
              "y":463},
            "size":{
              "width":263,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef727c77a9fd49af9dff7b1ded9dfacc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":854,
                  "y":463},
                "size":{
                  "width":263,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39afa339cd8d444881ac9a4c60de2807",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":295,
              "y":473},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32fa096cedb84dd1975bd06ddf45b900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":295,
                  "y":473},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c679bbeac8e343a98da77bd0457b63f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":175,
              "y":739},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eba1157584c4697a6cb5216a70b144c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":175,
                  "y":739},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d94af976ac914f6fb90877732f9605ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":622,
              "y":505},
            "size":{
              "width":279,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03131fcd5f89486e9b1f4682589e704b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":622,
                  "y":505},
                "size":{
                  "width":279,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u26.png"}},
{
          "id":"c49f5c6126634ba39500ec194c5e6ed3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":731,
              "y":515},
            "size":{
              "width":159,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4b6d5c7093e47c0b338f37d077823e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":731,
                  "y":515},
                "size":{
                  "width":159,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8af87fa26bfb40fcaf222a48aa9e1137",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Negreta', 'Agency FB'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":644,
              "y":511},
            "size":{
              "width":49,
              "height":45},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a665cc083ee34838adc6e5f05af8e631",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Negreta', 'Agency FB'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":644,
                  "y":511},
                "size":{
                  "width":49,
                  "height":45},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录流程/u30.png"}},
{
          "id":"e32093802d814a7993b0a7d0f9074b96",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":709,
              "y":511},
            "size":{
              "width":10,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录流程/u32_line.png"}},
{
          "id":"bd988207e54c436682682e8c26adc291",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":926,
              "y":521},
            "size":{
              "width":209,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"395b6a3805764ae8bd906a97fdd9119c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":926,
                  "y":521},
                "size":{
                  "width":209,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91a04c9f85a84a03a9f3705d50bad24f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":420},
            "size":{
              "width":1102,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页动态条/u98_line.png"}},
{
          "id":"a115a21401d24b2aa6c4325ec80f204f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":622,
              "y":623},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b54e39fcea49c69e7483d61422b104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":622,
                  "y":623},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a71063f79ab74231a886443ff0ba358c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":622,
              "y":595},
            "size":{
              "width":360,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20064fa2d13f46918cf803541de77aeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":622,
                  "y":595},
                "size":{
                  "width":360,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8caf2451ccc54d6e8b9d599d706d81c2":{
      "scriptId":"u0"},
    "0be74241e1424df58ff5df66113c6d07":{
      "scriptId":"u1"},
    "4396efa33e814956babe5b919ffe4223":{
      "scriptId":"u2"},
    "de9859debf1c44d8a0d03616f009c7cc":{
      "scriptId":"u3"},
    "199990b2295c4ca0899c696c688a9fe1":{
      "scriptId":"u4"},
    "3b32dc8a113e4f2e974d5d7565e0522e":{
      "scriptId":"u5"},
    "f5a700b2b7374e5884b705a1b922cc5e":{
      "scriptId":"u6"},
    "769e9ab0bf0c493182a97d1de5637c02":{
      "scriptId":"u7"},
    "fe15f05a165e4f59b70612c5b488b1a4":{
      "scriptId":"u8"},
    "276beda77e264b1f800a9ab0ba454ae9":{
      "scriptId":"u9"},
    "f3819d4ebaef491e9c5a73f1b682c7d0":{
      "scriptId":"u10"},
    "bea449b0785a44ba93a2abb4d9f4f504":{
      "scriptId":"u11"},
    "3707efb66d8f4c1d978f706f7883778e":{
      "scriptId":"u12"},
    "b7714799355244388995eddb715527a7":{
      "scriptId":"u13"},
    "d1c5c4e5b6434656b1552b7859a4d77d":{
      "scriptId":"u14"},
    "a24d3987eb134d76909bda7c4c48b04c":{
      "scriptId":"u15"},
    "656c4923fd234328828cb73e27f7aed8":{
      "scriptId":"u16"},
    "6df9a8512b5b456ca6b2f98ea510a7bf":{
      "scriptId":"u17"},
    "f1408294ebbd433f93fc9ed4e37287f2":{
      "scriptId":"u18"},
    "4594108bcb734ab8be539949496b45f1":{
      "scriptId":"u19"},
    "3af10500baba452fa3312bf87f2bf3e3":{
      "scriptId":"u20"},
    "d186c1dd085644149643233e89a02d3d":{
      "scriptId":"u21"},
    "13d93ed8596148b384e27bd5f1f094c0":{
      "scriptId":"u22"},
    "28cd455ce772410f833d96d9464cd318":{
      "scriptId":"u23"},
    "81ee9f53ab8d4fedb9a1c06f1e318444":{
      "scriptId":"u24"},
    "1a628775d7684390ae155ce07c6b4371":{
      "scriptId":"u25"},
    "a10d387ded024150a775b2a0f330ba06":{
      "scriptId":"u26"},
    "a096c5cd9d90405f89963c1d428b0f8d":{
      "scriptId":"u27"},
    "0460795265044ba7bc134e09f08a7b6f":{
      "scriptId":"u28"},
    "95edb97025ee44cf9a1004f6f2f39fd0":{
      "scriptId":"u29"},
    "b7793b4e07924f9db00a134fafa7802b":{
      "scriptId":"u30"},
    "636fc7369bf1483485e75f8c23f63fd1":{
      "scriptId":"u31"},
    "976c9b9e8902450791b81af1a3968d0a":{
      "scriptId":"u32"},
    "bbe348cce3af4fbd8af39ccaad1fff92":{
      "scriptId":"u33"},
    "f6b1eadaa2bb448e9e77983522e02c4b":{
      "scriptId":"u34"},
    "06d5de7173a9444aa4d882ed96fd44b2":{
      "scriptId":"u35"},
    "85c19db49e6d4c5d9079a25d6b8db737":{
      "scriptId":"u36"},
    "8e16645c50364fdca9ab619c15b82993":{
      "scriptId":"u37"},
    "5037ef93898d436490078366a3ea4df1":{
      "scriptId":"u38"},
    "38160e290312456a83ed8fa7d0ce8cfd":{
      "scriptId":"u39"},
    "f44439cf2bb04ac4ad4c3e77f8eebe38":{
      "scriptId":"u40"},
    "138254c8892547bbae9b281d97ca4ac7":{
      "scriptId":"u41"},
    "24e5e6c742374dc0a971122b0cbab8f3":{
      "scriptId":"u42"},
    "056507b2f4a74636988da50067b40d30":{
      "scriptId":"u43"},
    "43158369a3a94113bc572aaf7d9b383a":{
      "scriptId":"u44"},
    "e0ee2df9c8354af9b77725a88127239a":{
      "scriptId":"u45"},
    "dc7efd2552034abfb817935aabd8e2b4":{
      "scriptId":"u46"},
    "6c2f76bddf844d098f5cfdcb4f1df43c":{
      "scriptId":"u47"},
    "57c3ecd212194e258fb3fd593e499eba":{
      "scriptId":"u48"},
    "922800ee38014b3fb1e58b697a1952ef":{
      "scriptId":"u49"},
    "5af31a2cb22e4c5a9723b08274d1c3fa":{
      "scriptId":"u50"},
    "7c075af05cfd4616b90c480454d5d9e7":{
      "scriptId":"u51"},
    "5b243b0516ab420995a69b0075681bfe":{
      "scriptId":"u52"},
    "f37a15f8590d46bd9443ae42d50dd4da":{
      "scriptId":"u53"},
    "2d319ac492334cb38641df1bccdc8260":{
      "scriptId":"u54"},
    "bde6a55235e34b0ea6b7afa3eca841f3":{
      "scriptId":"u55"},
    "d98206103cf740238bc0e8f95d02f167":{
      "scriptId":"u56"},
    "802cfeef08d64a568ee27e799d8cf3fe":{
      "scriptId":"u57"},
    "f22cea1fa36f4a23b0a63f77e4a31d39":{
      "scriptId":"u58"},
    "c7e4d39079da44fd996bce8e875bbcad":{
      "scriptId":"u59"},
    "30c7d39cd7b54f32a4ff4e3a6f299cac":{
      "scriptId":"u60"},
    "2d50d54c3a5544b6b834bdebca818a8c":{
      "scriptId":"u61"},
    "f03277f4ba8b4b5095b1089f74556ab1":{
      "scriptId":"u62"},
    "79b74a0e117a4d91acf0ec879e4bf8b5":{
      "scriptId":"u63"},
    "b5161cb4ed8542c999cb75f4562220ad":{
      "scriptId":"u64"},
    "a644f6f019d04ae7a899ae08c3a30575":{
      "scriptId":"u65"},
    "32e3aa5b611e4ed4a079a9a59c6ddc0d":{
      "scriptId":"u66"},
    "48d16c3f38114840a170919ffb90a916":{
      "scriptId":"u67"},
    "c5ca6bc6d6534363b0a47c3c7ef7c36d":{
      "scriptId":"u68"},
    "aff6930ed6954c24a41e044e3c0f7165":{
      "scriptId":"u69"},
    "7922cbc86233420eabe13138e8044561":{
      "scriptId":"u70"},
    "cfdb5edcf36d49c69c23371c35a82c5c":{
      "scriptId":"u71"},
    "3cb24a1835e74857be839118625d2244":{
      "scriptId":"u72"},
    "f08e5c906d6a409dbd66b4356e7db353":{
      "scriptId":"u73"},
    "854eb626ddfd4a13a4bcd565fc59f3f5":{
      "scriptId":"u74"},
    "480debd1972e427f96e7ada97c71fdb5":{
      "scriptId":"u75"},
    "993015d7b0354585937d90cd5d45e140":{
      "scriptId":"u76"},
    "5f47b327168e4823bfe44e63a0763c3c":{
      "scriptId":"u77"},
    "318d975eff97464da69009c92a809086":{
      "scriptId":"u78"},
    "a8badd1cc029476b8da62f7f9177ab57":{
      "scriptId":"u79"},
    "e6ec5e0ef1bc4efabf7e9f70447d3f9d":{
      "scriptId":"u80"},
    "dc69d3e8938f4baaafc544738a483a1f":{
      "scriptId":"u81"},
    "43ef523a36e34b5a963d4abe85cc3568":{
      "scriptId":"u82"},
    "8a0558fa87564710a8cb307cce7e6727":{
      "scriptId":"u83"},
    "ef727c77a9fd49af9dff7b1ded9dfacc":{
      "scriptId":"u84"},
    "39afa339cd8d444881ac9a4c60de2807":{
      "scriptId":"u85"},
    "32fa096cedb84dd1975bd06ddf45b900":{
      "scriptId":"u86"},
    "c679bbeac8e343a98da77bd0457b63f1":{
      "scriptId":"u87"},
    "5eba1157584c4697a6cb5216a70b144c":{
      "scriptId":"u88"},
    "d94af976ac914f6fb90877732f9605ac":{
      "scriptId":"u89"},
    "03131fcd5f89486e9b1f4682589e704b":{
      "scriptId":"u90"},
    "c49f5c6126634ba39500ec194c5e6ed3":{
      "scriptId":"u91"},
    "a4b6d5c7093e47c0b338f37d077823e9":{
      "scriptId":"u92"},
    "8af87fa26bfb40fcaf222a48aa9e1137":{
      "scriptId":"u93"},
    "a665cc083ee34838adc6e5f05af8e631":{
      "scriptId":"u94"},
    "e32093802d814a7993b0a7d0f9074b96":{
      "scriptId":"u95"},
    "bd988207e54c436682682e8c26adc291":{
      "scriptId":"u96"},
    "395b6a3805764ae8bd906a97fdd9119c":{
      "scriptId":"u97"},
    "91a04c9f85a84a03a9f3705d50bad24f":{
      "scriptId":"u98"},
    "a115a21401d24b2aa6c4325ec80f204f":{
      "scriptId":"u99"},
    "d5b54e39fcea49c69e7483d61422b104":{
      "scriptId":"u100"},
    "a71063f79ab74231a886443ff0ba358c":{
      "scriptId":"u101"},
    "20064fa2d13f46918cf803541de77aeb":{
      "scriptId":"u102"}}});