$axure.loadCurrentPage({
  "url":"挂号偏方.html",
  "generationDate":new Date(1483009543278.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f30d2c43a37a49b1b0baa207f31814c8",
    "type":"Axure:Page",
    "name":"挂号偏方",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"519fcf62d5974dab8b5727e4b2bec3bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":537},
            "size":{
              "width":281,
              "height":454},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42599f0e71224d76a0be4da323d332de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":537},
                "size":{
                  "width":281,
                  "height":454},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u0.png"}},
{
          "id":"a41f139fc99246c5a4437e97675b2499",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":548},
            "size":{
              "width":20,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acd1062fe99945a2b0ecd3e3c5e65b0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":548},
                "size":{
                  "width":20,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e826ae68164d4a13ba33bd627b60d863",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":539},
            "size":{
              "width":276,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46a24ce5162c4a19a0b52ad0d19c1fec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":539},
                "size":{
                  "width":276,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u4.png"}},
{
          "id":"d38aef15b61341999f3dff2f2d831313",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":545},
            "size":{
              "width":68,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eee17523db04ab699bd1428de0e90ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":545},
                "size":{
                  "width":68,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u6.png"}},
{
          "id":"af45a862b2ea4723a737f11232b573fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":189,
              "y":547},
            "size":{
              "width":49,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c70dda470ec4f09a3751dc0ebdd4b35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":189,
                  "y":547},
                "size":{
                  "width":49,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbbe2a3f3f6e45d285c676077504db63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":163,
              "y":573},
            "size":{
              "width":277,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b62e5d5b49412d860d4b9450270668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":163,
                  "y":573},
                "size":{
                  "width":277,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u10.png"}},
{
          "id":"7eeca6a3277144e38767b3e901adf3f6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":818},
            "size":{
              "width":283,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/自我诊断/u10_line.png"}},
{
          "id":"ddb6a08beae34c01a3d3e059dbf950bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":590},
            "size":{
              "width":39,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"134749f448c34cb1bbecdeb3c34d56fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":590},
                "size":{
                  "width":39,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u20.png"}},
{
          "id":"e791719510bc46a8aa99f54c4c639076",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":213,
              "y":600},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"395a51794abd4ed9ac7fd54330111049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":213,
                  "y":600},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f28375226ca548679e83ca084b7ffbbf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":829},
            "size":{
              "width":39,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2170be719c04428b3f56840c8d0dcc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":829},
                "size":{
                  "width":39,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u20.png"}},
{
          "id":"75b1843304f84b3e8fb8b9af0792450c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"22px",
            "fontWeight":"400",
            "location":{
              "x":213,
              "y":840},
            "size":{
              "width":89,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a9b0db36eb14acea749b339fc2a1645",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"22px",
                "fontWeight":"400",
                "location":{
                  "x":213,
                  "y":840},
                "size":{
                  "width":89,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"811d1c0b85804c49a6af10224fcecdf1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":646},
            "size":{
              "width":50,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ae2412c6b794231854c66750c4f10ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":646},
                "size":{
                  "width":50,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u21.png"}},
{
          "id":"82cd7cbdbb7c43f88168c8a280b5c81d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":646},
            "size":{
              "width":50,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6c9d463ca7f46eba144af441ac749b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":646},
                "size":{
                  "width":50,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u21.png"}},
{
          "id":"21e1e372aeca4a3e87d693c128a1c6dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":646},
            "size":{
              "width":50,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf5dd01ac2ab45d29f3d37a6c34cfb8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":646},
                "size":{
                  "width":50,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u21.png"}},
{
          "id":"612a6300ea2e4822afa01ee7b90f6c06",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":646},
            "size":{
              "width":50,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d895b68e5d04cc38e8f34e5a313cc05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":646},
                "size":{
                  "width":50,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u21.png"}},
{
          "id":"931ddc8a0bbd40a3b66872bd83d242c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":733},
            "size":{
              "width":50,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b245b7ac3c3841ffa45107ad880598cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":733},
                "size":{
                  "width":50,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u21.png"}},
{
          "id":"7fc11245ff77483bb3f419f18f34f5f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":733},
            "size":{
              "width":50,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbf33bf510c54ace94b903db46199648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":733},
                "size":{
                  "width":50,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u21.png"}},
{
          "id":"796fc8a6ed7247c09fbb18a0e5e2b339",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":733},
            "size":{
              "width":50,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1920e827f42400289c18cee7da408e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":733},
                "size":{
                  "width":50,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u21.png"}},
{
          "id":"54473b7cd16f4690abbae9ec9c0e6f3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":733},
            "size":{
              "width":50,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42a74ad197ec4d1581fbf9e093c8ccd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":733},
                "size":{
                  "width":50,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u21.png"}},
{
          "id":"5622bd25fddc48f2a6d332381641c46c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":178,
              "y":701},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ed0bf506ac9469aab4d8fcfb0a10592",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":178,
                  "y":701},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff5770c91e7c417d9a3c252449ac8e71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":249,
              "y":701},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7af7586d2ad468fae532dc7212441bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":249,
                  "y":701},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd516f1e1a6e427da80d991721bc4189",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":323,
              "y":701},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5695755ef4654535abdfcc8f3fea06ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":323,
                  "y":701},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"479733edaa744e3d87a634f6943570b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":389,
              "y":701},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e9c085ec56a4c228704159dfa1febbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":389,
                  "y":701},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"464c5a03bc5d4599aca739335dafb484",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":178,
              "y":789},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88998aebf6a24015aed17ab1656a0ec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":178,
                  "y":789},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5da95db358e4f17973b576b6d81c3a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":249,
              "y":789},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ed728b5dff64b52af9685fc38cbb5e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":249,
                  "y":789},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44c332a2d4f4447aa3b19785d1de4918",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":323,
              "y":789},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3423390c510a4df9a3726bc4c3c22607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":323,
                  "y":789},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bebd9b464d514aa394e7253e45e7ee98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":389,
              "y":789},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"604b24788e294197867a8abfe247ce38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":389,
                  "y":789},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ba4eefcfdaa4816a2b5c95e082f6ccf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":885},
            "size":{
              "width":80,
              "height":38},
            "cornerRadiusTopLeft":"14"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9c74fdd275d4d3d84f66467734a17f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":885},
                "size":{
                  "width":80,
                  "height":38},
                "cornerRadiusTopLeft":"14"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u53.png"}},
{
          "id":"986509d1524f4bd28648e647570c6f14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":159,
              "y":37},
            "size":{
              "width":282,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ffdd079a98a40d38cde57f47822d2b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":159,
                  "y":37},
                "size":{
                  "width":282,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u55.png"}},
{
          "id":"15da2a606ce94fa593cd546325e004b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":885},
            "size":{
              "width":80,
              "height":38},
            "cornerRadiusTopLeft":"14"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cdf88d3f87b4b7eafe15563ea343219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":885},
                "size":{
                  "width":80,
                  "height":38},
                "cornerRadiusTopLeft":"14"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u53.png"}},
{
          "id":"dcf6c4a914eb493c86ef3ecb6d580451",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":885},
            "size":{
              "width":80,
              "height":38},
            "cornerRadiusTopLeft":"14"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f529c7bf6c4ff8adb75609011f988a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":885},
                "size":{
                  "width":80,
                  "height":38},
                "cornerRadiusTopLeft":"14"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u53.png"}},
{
          "id":"b349a549884e43f491394c5b243643ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":934},
            "size":{
              "width":80,
              "height":38},
            "cornerRadiusTopLeft":"14"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"001bc2a137af401780e0b406e5f18c19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":934},
                "size":{
                  "width":80,
                  "height":38},
                "cornerRadiusTopLeft":"14"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u53.png"}},
{
          "id":"3076eb408bf44358b4436ede81ca0d8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":934},
            "size":{
              "width":80,
              "height":38},
            "cornerRadiusTopLeft":"14"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7fe90176e894714a737b91d2911d7e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":934},
                "size":{
                  "width":80,
                  "height":38},
                "cornerRadiusTopLeft":"14"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u53.png"}},
{
          "id":"d2a20fcc338644b998f8413f9a0062e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":934},
            "size":{
              "width":80,
              "height":38},
            "cornerRadiusTopLeft":"14"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61314080062c45048ea63d8de7e5112a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":934},
                "size":{
                  "width":80,
                  "height":38},
                "cornerRadiusTopLeft":"14"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u53.png"}},
{
          "id":"1f8b9843f645445c999d187531edb89c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":86},
            "size":{
              "width":277,
              "height":39},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36286dba2bc54d679286c681437bc0f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":86},
                "size":{
                  "width":277,
                  "height":39},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u67.png"}},
{
          "id":"bc3c130f14304bf6bc974379f6a1d00b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":272},
            "size":{
              "width":277,
              "height":212},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22d1ca6898724522b9f4110a62ec3f4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":272},
                "size":{
                  "width":277,
                  "height":212},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u69.png"}},
{
          "id":"257ce258bab041e6926d4959c54613d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":484},
            "size":{
              "width":277,
              "height":30},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eefae0d4c9834ca9af50387a21a45f71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":484},
                "size":{
                  "width":277,
                  "height":30},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u71.png"}},
{
          "id":"4561538e33714616ad76af22e97d36ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":70,
              "y":37},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d51ebdca13243e5b2b4631cfe81f91f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":70,
                  "y":37},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b5ce0351b034ef48029659f659abe5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":70,
              "y":91},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5fe714580df4e25aa95153b98457867",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":70,
                  "y":91},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e66285f750749199f463b48826e2964",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":49},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed3fd6accfc4466f912b6a308229d75e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":49},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f2e1bef2206402d980d63c3a61bc204",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":125},
            "size":{
              "width":277,
              "height":212},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65716931bb8f40a2a859020f8d51441a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":125},
                "size":{
                  "width":277,
                  "height":212},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u69.png"}},
{
          "id":"4025a4b6a33d4fe2ad2ccb6c875ddefb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":49},
            "size":{
              "width":73,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e4915dd2b4a416fb817b0ed5bf4833f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":49},
                "size":{
                  "width":73,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "519fcf62d5974dab8b5727e4b2bec3bb":{
      "scriptId":"u0"},
    "42599f0e71224d76a0be4da323d332de":{
      "scriptId":"u1"},
    "a41f139fc99246c5a4437e97675b2499":{
      "scriptId":"u2"},
    "acd1062fe99945a2b0ecd3e3c5e65b0a":{
      "scriptId":"u3"},
    "e826ae68164d4a13ba33bd627b60d863":{
      "scriptId":"u4"},
    "46a24ce5162c4a19a0b52ad0d19c1fec":{
      "scriptId":"u5"},
    "d38aef15b61341999f3dff2f2d831313":{
      "scriptId":"u6"},
    "2eee17523db04ab699bd1428de0e90ba":{
      "scriptId":"u7"},
    "af45a862b2ea4723a737f11232b573fa":{
      "scriptId":"u8"},
    "1c70dda470ec4f09a3751dc0ebdd4b35":{
      "scriptId":"u9"},
    "dbbe2a3f3f6e45d285c676077504db63":{
      "scriptId":"u10"},
    "29b62e5d5b49412d860d4b9450270668":{
      "scriptId":"u11"},
    "7eeca6a3277144e38767b3e901adf3f6":{
      "scriptId":"u12"},
    "ddb6a08beae34c01a3d3e059dbf950bc":{
      "scriptId":"u13"},
    "134749f448c34cb1bbecdeb3c34d56fe":{
      "scriptId":"u14"},
    "e791719510bc46a8aa99f54c4c639076":{
      "scriptId":"u15"},
    "395a51794abd4ed9ac7fd54330111049":{
      "scriptId":"u16"},
    "f28375226ca548679e83ca084b7ffbbf":{
      "scriptId":"u17"},
    "e2170be719c04428b3f56840c8d0dcc6":{
      "scriptId":"u18"},
    "75b1843304f84b3e8fb8b9af0792450c":{
      "scriptId":"u19"},
    "4a9b0db36eb14acea749b339fc2a1645":{
      "scriptId":"u20"},
    "811d1c0b85804c49a6af10224fcecdf1":{
      "scriptId":"u21"},
    "2ae2412c6b794231854c66750c4f10ae":{
      "scriptId":"u22"},
    "82cd7cbdbb7c43f88168c8a280b5c81d":{
      "scriptId":"u23"},
    "f6c9d463ca7f46eba144af441ac749b0":{
      "scriptId":"u24"},
    "21e1e372aeca4a3e87d693c128a1c6dc":{
      "scriptId":"u25"},
    "bf5dd01ac2ab45d29f3d37a6c34cfb8e":{
      "scriptId":"u26"},
    "612a6300ea2e4822afa01ee7b90f6c06":{
      "scriptId":"u27"},
    "5d895b68e5d04cc38e8f34e5a313cc05":{
      "scriptId":"u28"},
    "931ddc8a0bbd40a3b66872bd83d242c8":{
      "scriptId":"u29"},
    "b245b7ac3c3841ffa45107ad880598cb":{
      "scriptId":"u30"},
    "7fc11245ff77483bb3f419f18f34f5f3":{
      "scriptId":"u31"},
    "bbf33bf510c54ace94b903db46199648":{
      "scriptId":"u32"},
    "796fc8a6ed7247c09fbb18a0e5e2b339":{
      "scriptId":"u33"},
    "d1920e827f42400289c18cee7da408e0":{
      "scriptId":"u34"},
    "54473b7cd16f4690abbae9ec9c0e6f3c":{
      "scriptId":"u35"},
    "42a74ad197ec4d1581fbf9e093c8ccd6":{
      "scriptId":"u36"},
    "5622bd25fddc48f2a6d332381641c46c":{
      "scriptId":"u37"},
    "6ed0bf506ac9469aab4d8fcfb0a10592":{
      "scriptId":"u38"},
    "ff5770c91e7c417d9a3c252449ac8e71":{
      "scriptId":"u39"},
    "b7af7586d2ad468fae532dc7212441bc":{
      "scriptId":"u40"},
    "cd516f1e1a6e427da80d991721bc4189":{
      "scriptId":"u41"},
    "5695755ef4654535abdfcc8f3fea06ba":{
      "scriptId":"u42"},
    "479733edaa744e3d87a634f6943570b9":{
      "scriptId":"u43"},
    "6e9c085ec56a4c228704159dfa1febbb":{
      "scriptId":"u44"},
    "464c5a03bc5d4599aca739335dafb484":{
      "scriptId":"u45"},
    "88998aebf6a24015aed17ab1656a0ec9":{
      "scriptId":"u46"},
    "a5da95db358e4f17973b576b6d81c3a9":{
      "scriptId":"u47"},
    "5ed728b5dff64b52af9685fc38cbb5e5":{
      "scriptId":"u48"},
    "44c332a2d4f4447aa3b19785d1de4918":{
      "scriptId":"u49"},
    "3423390c510a4df9a3726bc4c3c22607":{
      "scriptId":"u50"},
    "bebd9b464d514aa394e7253e45e7ee98":{
      "scriptId":"u51"},
    "604b24788e294197867a8abfe247ce38":{
      "scriptId":"u52"},
    "0ba4eefcfdaa4816a2b5c95e082f6ccf":{
      "scriptId":"u53"},
    "d9c74fdd275d4d3d84f66467734a17f1":{
      "scriptId":"u54"},
    "986509d1524f4bd28648e647570c6f14":{
      "scriptId":"u55"},
    "2ffdd079a98a40d38cde57f47822d2b2":{
      "scriptId":"u56"},
    "15da2a606ce94fa593cd546325e004b1":{
      "scriptId":"u57"},
    "7cdf88d3f87b4b7eafe15563ea343219":{
      "scriptId":"u58"},
    "dcf6c4a914eb493c86ef3ecb6d580451":{
      "scriptId":"u59"},
    "f5f529c7bf6c4ff8adb75609011f988a":{
      "scriptId":"u60"},
    "b349a549884e43f491394c5b243643ab":{
      "scriptId":"u61"},
    "001bc2a137af401780e0b406e5f18c19":{
      "scriptId":"u62"},
    "3076eb408bf44358b4436ede81ca0d8d":{
      "scriptId":"u63"},
    "e7fe90176e894714a737b91d2911d7e4":{
      "scriptId":"u64"},
    "d2a20fcc338644b998f8413f9a0062e7":{
      "scriptId":"u65"},
    "61314080062c45048ea63d8de7e5112a":{
      "scriptId":"u66"},
    "1f8b9843f645445c999d187531edb89c":{
      "scriptId":"u67"},
    "36286dba2bc54d679286c681437bc0f8":{
      "scriptId":"u68"},
    "bc3c130f14304bf6bc974379f6a1d00b":{
      "scriptId":"u69"},
    "22d1ca6898724522b9f4110a62ec3f4f":{
      "scriptId":"u70"},
    "257ce258bab041e6926d4959c54613d0":{
      "scriptId":"u71"},
    "eefae0d4c9834ca9af50387a21a45f71":{
      "scriptId":"u72"},
    "4561538e33714616ad76af22e97d36ae":{
      "scriptId":"u73"},
    "7d51ebdca13243e5b2b4631cfe81f91f":{
      "scriptId":"u74"},
    "4b5ce0351b034ef48029659f659abe5a":{
      "scriptId":"u75"},
    "b5fe714580df4e25aa95153b98457867":{
      "scriptId":"u76"},
    "4e66285f750749199f463b48826e2964":{
      "scriptId":"u77"},
    "ed3fd6accfc4466f912b6a308229d75e":{
      "scriptId":"u78"},
    "3f2e1bef2206402d980d63c3a61bc204":{
      "scriptId":"u79"},
    "65716931bb8f40a2a859020f8d51441a":{
      "scriptId":"u80"},
    "4025a4b6a33d4fe2ad2ccb6c875ddefb":{
      "scriptId":"u81"},
    "3e4915dd2b4a416fb817b0ed5bf4833f":{
      "scriptId":"u82"}}});