$axure.loadCurrentPage({
  "url":"中间页交互.html",
  "generationDate":new Date(1481539892153.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"92e0ed96418e40f88be55e9cd4ad059e",
    "type":"Axure:Page",
    "name":"中间页交互",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"60f0aa28ae924cb0829b4ad61af283ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":124},
            "size":{
              "width":321,
              "height":571}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e28535e787b24bce8f808824355f9992",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":124},
                "size":{
                  "width":321,
                  "height":571}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u95.jpg"}},
{
          "id":"0c991b9b737b4241b52056dcd841b968",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":232},
            "size":{
              "width":321,
              "height":144},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15be7c56269e4dd293b6d27ab4188994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":232},
                "size":{
                  "width":321,
                  "height":144},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u2.png"}},
{
          "id":"456d1fd254bf47d380efb7a9bf293f09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":480},
            "size":{
              "width":321,
              "height":143},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ec5c6898a8f49f9bba98e84880c1eb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":480},
                "size":{
                  "width":321,
                  "height":143},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u4.png"}},
{
          "id":"08f61dadf8ca42beb1b390e574a30b40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":623},
            "size":{
              "width":321,
              "height":72},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cc7e113cc0d48d4bd3a0df7b0d32840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":623},
                "size":{
                  "width":321,
                  "height":72},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u6.png"}},
{
          "id":"e90487620b194ef3b63a85952a2f32ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":375},
            "size":{
              "width":321,
              "height":106},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a579baedf6ae45f09598f98c3f7bfa24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":375},
                "size":{
                  "width":321,
                  "height":106},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u8.png"}},
{
          "id":"fd7d0e78e50345a7a07c58540d3771f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":781,
              "y":338},
            "size":{
              "width":321,
              "height":1285},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36243b85fc0f41a3a2e5e7f86f448a6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":781,
                  "y":338},
                "size":{
                  "width":321,
                  "height":1285},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u10.png"}},
{
          "id":"d6856e62b8ff430dbeeb214e18045d42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1136,
              "y":127},
            "size":{
              "width":321,
              "height":213},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"922482fd159b45e58206dea4503b8e5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1136,
                  "y":127},
                "size":{
                  "width":321,
                  "height":213},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u12.png"}},
{
          "id":"7f2a7c6263804f13bab169410e3b4b97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1136,
              "y":444},
            "size":{
              "width":321,
              "height":141},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"743359918d814ceea3cdd75129bbfc56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1136,
                  "y":444},
                "size":{
                  "width":321,
                  "height":141},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u14.png"}},
{
          "id":"50241ef5bbcc4951b26d906e61c112bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1136,
              "y":585},
            "size":{
              "width":321,
              "height":109},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0d21697bfb24637b224616ddf67e019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1136,
                  "y":585},
                "size":{
                  "width":321,
                  "height":109},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u16.png"}},
{
          "id":"1f06c3f085fd43b48dac8f9e8759b5c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1489,
              "y":124},
            "size":{
              "width":321,
              "height":571}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c4993bd0454507b36cdac74e96b94e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1489,
                  "y":124},
                "size":{
                  "width":321,
                  "height":571}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u18.jpg"}},
{
          "id":"da245cb7875f4149a2cfdc59e06a696c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":728},
            "size":{
              "width":321,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df86f274f7c74258b29709e7f5959323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":728},
                "size":{
                  "width":321,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5607654f84d0433cbfedbbd35198093a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":730},
            "size":{
              "width":259,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96e2cb38a2c240f2b3b100e3ceee5b08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":730},
                "size":{
                  "width":259,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00d489a406534325b118157301e2214e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":373},
            "size":{
              "width":251,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eaecaa9695c4697a86d65188aac8904",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":373},
                "size":{
                  "width":251,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e9e01bb12e240a787953741c566416c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1147,
              "y":705},
            "size":{
              "width":313,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65aaf1146dce400d9edb19ed82485e96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1147,
                  "y":705},
                "size":{
                  "width":313,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"897d8621912a49ae954f53c6cde651e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1489,
              "y":705},
            "size":{
              "width":381,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"497279949fc1405cbf6f5396658566d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1489,
                  "y":705},
                "size":{
                  "width":381,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33365a7d87ca478cbe26bf480cdfbd03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":702},
            "size":{
              "width":285,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfdb237d204d4a86976311c49d64cd9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":702},
                "size":{
                  "width":285,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f46f298aaed04422b59be6acd305440b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":72},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1028e78be77d4c12a61c6f2f07f0a868",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":72},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3838621c43b14f88bfa63a3e127b0f38",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":571,
              "y":80},
            "size":{
              "width":49,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35057468ec984ff3bd5fa85fdfe27516",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":571,
                  "y":80},
                "size":{
                  "width":49,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a081793ddb49482dbf945583967b08a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":896,
              "y":86},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78c9a2ff1c5d4c8590e36f7a49e4f85b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":896,
                  "y":86},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c54a1d0665e64eb097b4a4970afc3cdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1248,
              "y":86},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e3969fcac294863a3978b7ebc31dcbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1248,
                  "y":86},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81481048f7734ad981eaea7ccfd28a8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1577,
              "y":86},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c983275f56b24ea6ad723080ba0c1fc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1577,
                  "y":86},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"960c1eb3b0fe414391e4f396e384f852",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":781,
              "y":126},
            "size":{
              "width":321,
              "height":212},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff4be77ad8674974aba9e42eb1166584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":781,
                  "y":126},
                "size":{
                  "width":321,
                  "height":212},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u42.png"}},
{
          "id":"69ca9347cf8f4b60952edd34322e59ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":124},
            "size":{
              "width":321,
              "height":212},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1254a4ea5b2e4af3bc69d9a3d695a8ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":124},
                "size":{
                  "width":321,
                  "height":212},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u42.png"}},
{
          "id":"fbc204204cd045069926f7c012e4b751",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1136,
              "y":339},
            "size":{
              "width":321,
              "height":141},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71172ae1c4e54645b3cace317c835909",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1136,
                  "y":339},
                "size":{
                  "width":321,
                  "height":141},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u14.png"}},
{
          "id":"7e747624a45b49c3b98bc45739acaeb8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":137,
              "y":167},
            "size":{
              "width":192,
              "height":191}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"262306cebe6645aa908f8be030cec72c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":137,
                  "y":167},
                "size":{
                  "width":192,
                  "height":191}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小乐/u145.png"}},
{
          "id":"2685791ac0a1446eb268ce50e158ff0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x19000000},
            "location":{
              "x":75,
              "y":337},
            "size":{
              "width":321,
              "height":68},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7debc7463e4a438fa9772327eecb8719",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x19000000},
                "location":{
                  "x":75,
                  "y":337},
                "size":{
                  "width":321,
                  "height":68},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u50.png"}},
{
          "id":"7375f78390244488bc0f67daf297feb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":337},
            "size":{
              "width":321,
              "height":68},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":3,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"882ff8ba821f43849e6b633de1cd956a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":337},
                "size":{
                  "width":321,
                  "height":68},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":3,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/中间页交互/u52.png"}},
{
          "id":"d7492160b37a47ee8dd2cc08551d0800",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":212,
              "y":350},
            "size":{
              "width":158,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cdbd9838e33488bbad1ed544576ce44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":212,
                  "y":350},
                "size":{
                  "width":158,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb324e9e551647b0ae92b5dd43d4ff2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Agency FB Oblique', 'Agency FB'",
            "fontSize":"18px",
            "fontWeight":"400",
            "fontStyle":"oblique",
            "location":{
              "x":110,
              "y":347},
            "size":{
              "width":37,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b2d0bafc56849cd998172985f6f96b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Agency FB Oblique', 'Agency FB'",
                "fontSize":"18px",
                "fontWeight":"400",
                "fontStyle":"oblique",
                "location":{
                  "x":110,
                  "y":347},
                "size":{
                  "width":37,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcb0644e09114779b221b77fdea4efb3",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":344},
            "size":{
              "width":10,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/中间页交互/u58_line.png"}},
{
          "id":"2e60a73333024aa695b31d78b991c76c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":212,
              "y":372},
            "size":{
              "width":158,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44fe0d54a0c243778c10c9cd900cd575",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":212,
                  "y":372},
                "size":{
                  "width":158,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7552e1d2981d4b0fbdc693da61271251",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":-161,
              "y":940},
            "size":{
              "width":45,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康详情页/u111_line.png"}},
{
          "id":"611bc2ef753f448295694dc2890c4a33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":75,
              "y":930},
            "size":{
              "width":183,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99a8d7c304254fb19fcca2b20a93ea37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":930},
                "size":{
                  "width":183,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd9b1e5895b646afb2a6f6d9507f710a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":350,
              "y":930},
            "size":{
              "width":172,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0327806017b341559d16218cecc467d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":930},
                "size":{
                  "width":172,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"baa1239b2b244d56aa6c28cabae32bc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":75,
              "y":969},
            "size":{
              "width":259,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe58703ff4354fac8aab5a25882e5163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":969},
                "size":{
                  "width":259,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc65cdda067b4fc3abcf09ae1473bdf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":75,
              "y":1042},
            "size":{
              "width":213,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e9b964f40294f19be27ac59971088cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":1042},
                "size":{
                  "width":213,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c313fcbfbfd4796bd247b7c0b68bbe2",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":360},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14334f45ae624e7d8f9a1b417daacdbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":360},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}]},
{
          "id":"67f8b12360e043e395c6c5b2091b7f07",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":892},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a710ccde7fb407290726e3da99f6dfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":892},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5a8311a834041a7ba2472ecdf9b0cfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":1140},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7165c59a5f94d73ac2d529c652d158f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":1140},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "60f0aa28ae924cb0829b4ad61af283ab":{
      "scriptId":"u0"},
    "e28535e787b24bce8f808824355f9992":{
      "scriptId":"u1"},
    "0c991b9b737b4241b52056dcd841b968":{
      "scriptId":"u2"},
    "15be7c56269e4dd293b6d27ab4188994":{
      "scriptId":"u3"},
    "456d1fd254bf47d380efb7a9bf293f09":{
      "scriptId":"u4"},
    "9ec5c6898a8f49f9bba98e84880c1eb5":{
      "scriptId":"u5"},
    "08f61dadf8ca42beb1b390e574a30b40":{
      "scriptId":"u6"},
    "6cc7e113cc0d48d4bd3a0df7b0d32840":{
      "scriptId":"u7"},
    "e90487620b194ef3b63a85952a2f32ee":{
      "scriptId":"u8"},
    "a579baedf6ae45f09598f98c3f7bfa24":{
      "scriptId":"u9"},
    "fd7d0e78e50345a7a07c58540d3771f5":{
      "scriptId":"u10"},
    "36243b85fc0f41a3a2e5e7f86f448a6e":{
      "scriptId":"u11"},
    "d6856e62b8ff430dbeeb214e18045d42":{
      "scriptId":"u12"},
    "922482fd159b45e58206dea4503b8e5c":{
      "scriptId":"u13"},
    "7f2a7c6263804f13bab169410e3b4b97":{
      "scriptId":"u14"},
    "743359918d814ceea3cdd75129bbfc56":{
      "scriptId":"u15"},
    "50241ef5bbcc4951b26d906e61c112bf":{
      "scriptId":"u16"},
    "b0d21697bfb24637b224616ddf67e019":{
      "scriptId":"u17"},
    "1f06c3f085fd43b48dac8f9e8759b5c8":{
      "scriptId":"u18"},
    "61c4993bd0454507b36cdac74e96b94e":{
      "scriptId":"u19"},
    "da245cb7875f4149a2cfdc59e06a696c":{
      "scriptId":"u20"},
    "df86f274f7c74258b29709e7f5959323":{
      "scriptId":"u21"},
    "5607654f84d0433cbfedbbd35198093a":{
      "scriptId":"u22"},
    "96e2cb38a2c240f2b3b100e3ceee5b08":{
      "scriptId":"u23"},
    "00d489a406534325b118157301e2214e":{
      "scriptId":"u24"},
    "5eaecaa9695c4697a86d65188aac8904":{
      "scriptId":"u25"},
    "5e9e01bb12e240a787953741c566416c":{
      "scriptId":"u26"},
    "65aaf1146dce400d9edb19ed82485e96":{
      "scriptId":"u27"},
    "897d8621912a49ae954f53c6cde651e5":{
      "scriptId":"u28"},
    "497279949fc1405cbf6f5396658566d9":{
      "scriptId":"u29"},
    "33365a7d87ca478cbe26bf480cdfbd03":{
      "scriptId":"u30"},
    "bfdb237d204d4a86976311c49d64cd9a":{
      "scriptId":"u31"},
    "f46f298aaed04422b59be6acd305440b":{
      "scriptId":"u32"},
    "1028e78be77d4c12a61c6f2f07f0a868":{
      "scriptId":"u33"},
    "3838621c43b14f88bfa63a3e127b0f38":{
      "scriptId":"u34"},
    "35057468ec984ff3bd5fa85fdfe27516":{
      "scriptId":"u35"},
    "a081793ddb49482dbf945583967b08a0":{
      "scriptId":"u36"},
    "78c9a2ff1c5d4c8590e36f7a49e4f85b":{
      "scriptId":"u37"},
    "c54a1d0665e64eb097b4a4970afc3cdf":{
      "scriptId":"u38"},
    "5e3969fcac294863a3978b7ebc31dcbc":{
      "scriptId":"u39"},
    "81481048f7734ad981eaea7ccfd28a8b":{
      "scriptId":"u40"},
    "c983275f56b24ea6ad723080ba0c1fc1":{
      "scriptId":"u41"},
    "960c1eb3b0fe414391e4f396e384f852":{
      "scriptId":"u42"},
    "ff4be77ad8674974aba9e42eb1166584":{
      "scriptId":"u43"},
    "69ca9347cf8f4b60952edd34322e59ab":{
      "scriptId":"u44"},
    "1254a4ea5b2e4af3bc69d9a3d695a8ab":{
      "scriptId":"u45"},
    "fbc204204cd045069926f7c012e4b751":{
      "scriptId":"u46"},
    "71172ae1c4e54645b3cace317c835909":{
      "scriptId":"u47"},
    "7e747624a45b49c3b98bc45739acaeb8":{
      "scriptId":"u48"},
    "262306cebe6645aa908f8be030cec72c":{
      "scriptId":"u49"},
    "2685791ac0a1446eb268ce50e158ff0a":{
      "scriptId":"u50"},
    "7debc7463e4a438fa9772327eecb8719":{
      "scriptId":"u51"},
    "7375f78390244488bc0f67daf297feb6":{
      "scriptId":"u52"},
    "882ff8ba821f43849e6b633de1cd956a":{
      "scriptId":"u53"},
    "d7492160b37a47ee8dd2cc08551d0800":{
      "scriptId":"u54"},
    "9cdbd9838e33488bbad1ed544576ce44":{
      "scriptId":"u55"},
    "eb324e9e551647b0ae92b5dd43d4ff2e":{
      "scriptId":"u56"},
    "7b2d0bafc56849cd998172985f6f96b0":{
      "scriptId":"u57"},
    "bcb0644e09114779b221b77fdea4efb3":{
      "scriptId":"u58"},
    "2e60a73333024aa695b31d78b991c76c":{
      "scriptId":"u59"},
    "44fe0d54a0c243778c10c9cd900cd575":{
      "scriptId":"u60"},
    "7552e1d2981d4b0fbdc693da61271251":{
      "scriptId":"u61"},
    "611bc2ef753f448295694dc2890c4a33":{
      "scriptId":"u62"},
    "99a8d7c304254fb19fcca2b20a93ea37":{
      "scriptId":"u63"},
    "bd9b1e5895b646afb2a6f6d9507f710a":{
      "scriptId":"u64"},
    "0327806017b341559d16218cecc467d0":{
      "scriptId":"u65"},
    "baa1239b2b244d56aa6c28cabae32bc2":{
      "scriptId":"u66"},
    "fe58703ff4354fac8aab5a25882e5163":{
      "scriptId":"u67"},
    "dc65cdda067b4fc3abcf09ae1473bdf1":{
      "scriptId":"u68"},
    "5e9b964f40294f19be27ac59971088cb":{
      "scriptId":"u69"},
    "6c313fcbfbfd4796bd247b7c0b68bbe2":{
      "scriptId":"u70"},
    "14334f45ae624e7d8f9a1b417daacdbd":{
      "scriptId":"u71"},
    "67f8b12360e043e395c6c5b2091b7f07":{
      "scriptId":"u72"},
    "5a710ccde7fb407290726e3da99f6dfe":{
      "scriptId":"u73"},
    "a5a8311a834041a7ba2472ecdf9b0cfa":{
      "scriptId":"u74"},
    "e7165c59a5f94d73ac2d529c652d158f":{
      "scriptId":"u75"}}});