$axure.loadCurrentPage({
  "url":"微医合作（开发不用看）.html",
  "generationDate":new Date(1482750832875.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"35c4023bdc4e4c30b64d9a47e91a973a",
    "type":"Axure:Page",
    "name":"微医合作（开发不用看）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b3f6f8e60b764e79b1679b672e478159",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":114.5,
              "y":53},
            "size":{
              "width":179,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95bd633746db42f58987278ae4df64a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":114.5,
                  "y":53},
                "size":{
                  "width":179,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2842ec25b1c844eabf101744a574f262",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":147},
            "size":{
              "width":282,
              "height":145},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfbc7c25d783460894f087e419af34a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":461,
                  "y":147},
                "size":{
                  "width":282,
                  "height":145},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u69.png"}},
{
          "id":"e23846b667e04592ad5b21b0192dfc71",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":294},
            "size":{
              "width":282,
              "height":211},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62e4e067468a4778bf85fab5615eaf6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":461,
                  "y":294},
                "size":{
                  "width":282,
                  "height":211},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u71.png"}},
{
          "id":"177afb56cba14203adaf69670225fd40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":505},
            "size":{
              "width":282,
              "height":80},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8bac0d6a8d64d4185d1f9fffd34b4dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":461,
                  "y":505},
                "size":{
                  "width":282,
                  "height":80},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u73.png"}},
{
          "id":"abc574e363a641e5b94f92baa740c955",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":543,
              "y":230},
            "size":{
              "width":130,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49ab16a71f1547a4b7707ce0b330a419",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":543,
                  "y":230},
                "size":{
                  "width":130,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u75.png"}},
{
          "id":"dfe2bd57c0f140c58df3c803958c7ce1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":555,
              "y":147},
            "size":{
              "width":97,
              "height":104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc6de84c2c2045a28488298f6e63d19f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":555,
                  "y":147},
                "size":{
                  "width":97,
                  "height":104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u77.png"}},
{
          "id":"2d87ebd7f92048ca815dd14c7b890737",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":475,
              "y":149},
            "size":{
              "width":15,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8e02fdf58fe4c0988d62a94dc4164ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":475,
                  "y":149},
                "size":{
                  "width":15,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf71fd367fe3438aacc4c6ac20451db4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":463,
              "y":295},
            "size":{
              "width":280,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50e9907d40194ce5a51bf1f2b993e44e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":463,
                  "y":295},
                "size":{
                  "width":280,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u81.png"}},
{
          "id":"4211ee0dcf7c474da883c3effb619b6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":461,
              "y":140},
            "size":{
              "width":282,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94163222b8e744d39b9b9291a51a87b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":461,
                  "y":140},
                "size":{
                  "width":282,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u83.png"}},
{
          "id":"7cc2e55e7589489a8f41cd49a78a221d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":517,
              "y":321},
            "size":{
              "width":248,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/微医合作（开发不用看）/u18_line.png"}},
{
          "id":"13af1cc02b0f46a9a45eb9f32a061146",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":766,
              "y":311},
            "size":{
              "width":122,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7949fb6948d45efa9edecaa53d2e8c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":766,
                  "y":311},
                "size":{
                  "width":122,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ddb728b488949dd977596dcb06b2294",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":555,
              "y":215},
            "size":{
              "width":97,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ece5237ca794c9d916345fe807c1633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":555,
                  "y":215},
                "size":{
                  "width":97,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/挂号偏方/u88.png"}},
{
          "id":"91fc56de7909487ea4214a07af83fcae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":568,
              "y":213},
            "size":{
              "width":73,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"020d502c5a83405eb68cd6235396aea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":568,
                  "y":213},
                "size":{
                  "width":73,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c7cb211c3cb409d96d739a9abd2bc86",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":473,
              "y":295},
            "size":{
              "width":44,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf546ed1ccf14bfc9cd27ac3d8cd9b32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":473,
                  "y":295},
                "size":{
                  "width":44,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微医合作（开发不用看）/u25.png"}},
{
          "id":"f58fab2e04ec41fa895b318d37c44eb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":707},
            "size":{
              "width":179,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f70061f94a2462ca469e42817205de1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111,
                  "y":707},
                "size":{
                  "width":179,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a652096393e04137a9a102411cdaf887",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":67,
              "y":801},
            "size":{
              "width":278,
              "height":455},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f14d49e2aa941cda6ab49f5cb0bc609",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":67,
                  "y":801},
                "size":{
                  "width":278,
                  "height":455},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u0.png"}},
{
          "id":"ac3efb2944ad4415b519cd9fadfc1655",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":147,
              "y":762},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f85a2947136f4265852ba97493d9a8dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":147,
                  "y":762},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4903df8a638e4fa9be8208659f25fae1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":91,
              "y":828},
            "size":{
              "width":193,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96624e2eb1f24abb999f417e737dfb9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":91,
                  "y":828},
                "size":{
                  "width":193,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fda475028c174476bd5fdec21e9616dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":866},
            "size":{
              "width":264,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b61011b197ca4a88bb9124c72d7c3ef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":866},
                "size":{
                  "width":264,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u98.png"}},
{
          "id":"5c95653aac3d4b2593221e8c11d0c72e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":91,
              "y":975},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53c0287777e34a398e80ebaf2f88ed37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":91,
                  "y":975},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3091b8c9ce1044758495f1ffe5b38b41",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":1003},
            "size":{
              "width":264,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f65539e8d3794118a70bcd121030a80e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":1003},
                "size":{
                  "width":264,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u98.png"}},
{
          "id":"734b117aac1a442d807f71d512a90622",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":799},
            "size":{
              "width":279,
              "height":457},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37f37a62a1b740c187e57e9689dc2e09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":461,
                  "y":799},
                "size":{
                  "width":279,
                  "height":457},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微医合作（开发不用看）/u41.png"}},
{
          "id":"4a957e4da73b484b948359d3eea68fc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":565,
              "y":765},
            "size":{
              "width":82,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be01a32cbf35414d965dbcf946ee7059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":565,
                  "y":765},
                "size":{
                  "width":82,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dddac3a414d483997145efac8de75b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":1077},
            "size":{
              "width":264,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c75af4c81f842eea1bb5c3f1eae33e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":1077},
                "size":{
                  "width":264,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自我诊断/u98.png"}},
{
          "id":"7e1d821f0b5644e68baaa687d7ed9a9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":67,
              "y":147},
            "size":{
              "width":274,
              "height":378},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5b27f6e41af471a9410902138bfd0df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":67,
                  "y":147},
                "size":{
                  "width":274,
                  "height":378},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康详情状态/u0.png"}},
{
          "id":"bc4c8479483c47789da66249227b08d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":67,
              "y":443},
            "size":{
              "width":274,
              "height":147},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc15252882124e3c8bb11344eb063847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":67,
                  "y":443},
                "size":{
                  "width":274,
                  "height":147},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微医合作（开发不用看）/u49.png"}},
{
          "id":"bf91bebfa31f4d358a5cf3a67a9cfd57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF00CC33},
{
                  "color":0xFF00CC33},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9}]},
            "location":{
              "x":67,
              "y":147},
            "size":{
              "width":274,
              "height":212},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad2cb9deded74a5fa4f423b5315cf949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF00CC33},
{
                      "color":0xFF00CC33},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9}]},
                "location":{
                  "x":67,
                  "y":147},
                "size":{
                  "width":274,
                  "height":212},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康详情状态/u20.png"}},
{
          "id":"e6f7d5bce6a745b0a235146a4eccce78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":72,
              "y":285},
            "size":{
              "width":132,
              "height":104},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b520212bb3e44bd49a64c809e30a7fa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":72,
                  "y":285},
                "size":{
                  "width":132,
                  "height":104},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u92.png"}},
{
          "id":"5d096c06e05245d399e9b15b0d646028",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":204,
              "y":285},
            "size":{
              "width":132,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaa4a6f9ee0c44f6b5cdbb38083faa64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":204,
                  "y":285},
                "size":{
                  "width":132,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u94.png"}},
{
          "id":"95a17fab1c394972846d4535be8aa24c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":204,
              "y":337},
            "size":{
              "width":132,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9be8fab4bb194c089c8e22c645476612",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":204,
                  "y":337},
                "size":{
                  "width":132,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u94.png"}},
{
          "id":"51598581f75a40e496fe4f542696ec7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":389},
            "size":{
              "width":264,
              "height":97},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48f9d7dc47d5403a89d3da2d9dfbf11a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":389},
                "size":{
                  "width":264,
                  "height":97},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u80.png"}},
{
          "id":"39f865bd925e48a79cb885b1abd57f87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":483},
            "size":{
              "width":264,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9fed3b28e8843209a5e5813fd73e302",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":483},
                "size":{
                  "width":264,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u100.png"}},
{
          "id":"298b8d54d2db4a558874e8a1fb9f75f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":140},
            "size":{
              "width":105,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7af72fe55ad4437daead00d3a3602fd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":140},
                "size":{
                  "width":105,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1928c00e945f4fcea83474e58d63d26e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":93,
              "y":169},
            "size":{
              "width":34,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f834da9c40a541b2b5e53500279a5e5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":93,
                  "y":169},
                "size":{
                  "width":34,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u104.png"}},
{
          "id":"c5eadd2f71334353bbfc48b1380a1855",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":288,
              "y":169},
            "size":{
              "width":34,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baf1e3b3a8494302890a1a000a653411",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":288,
                  "y":169},
                "size":{
                  "width":34,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u104.png"}},
{
          "id":"6247e77b871f460d85d7a33ea73aa33d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "location":{
              "x":109,
              "y":304},
            "size":{
              "width":57,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aed5a89709f84384ba7d391d7c70b3f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "location":{
                  "x":109,
                  "y":304},
                "size":{
                  "width":57,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37076794d7bf4164bb19eab4f088e917",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":239,
              "y":300},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c705d07e5755409fa72f24a79d0d5cd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":239,
                  "y":300},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b28082b72fe243628deca642c3a0ba14",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":239,
              "y":354},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2529d532f6041df977340785006fed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":239,
                  "y":354},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f64d0dafc9ec42a49c48e42177ae5991",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":81,
              "y":400},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"418187e58b4b497c8263ea64ef4826f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":400},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaba985d21654fe8b9e24c179760f30f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":81,
              "y":498},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bc2f7ca3c954d51974bb17197f39c3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":498},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98ae8099152c46d9a19778f2d7888c43",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":137,
              "y":235},
            "size":{
              "width":122,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fd77fa3d22341e69b8fa5d045e7c5cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":235},
                "size":{
                  "width":122,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c4d6e4c2d9e45889cb670a7d85dded9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":218},
            "size":{
              "width":246,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康/u118_line.png"}},
{
          "id":"236e178c430041a7a1bb6ca7034a0d18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":93,
              "y":238},
            "size":{
              "width":34,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b561271025014d0d916f1d594aa39a41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":93,
                  "y":238},
                "size":{
                  "width":34,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u104.png"}},
{
          "id":"8f9905c85a244f6686cfad6ed79759f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":87,
              "y":431},
            "size":{
              "width":42,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9883f0ebc4b47f1b65e3d630a50f856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":87,
                  "y":431},
                "size":{
                  "width":42,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u121.png"}},
{
          "id":"c0a14a202c124a8bb1050d59158979fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":84,
              "y":443},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"669231eab769442bb5dd7eec8f95946c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":84,
                  "y":443},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de5323b08c2145d6bdd771a57c718c89",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":89,
              "y":537},
            "size":{
              "width":33,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4771af9669744f384dad512dba8e234",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":537},
                "size":{
                  "width":33,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c433536e2b34277a3366dc62d6a0c12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":432},
            "size":{
              "width":185,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f78558026d1432fb7d3222b39e21037",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":432},
                "size":{
                  "width":185,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u127.png"}},
{
          "id":"2c08b34c3e4e44feaabf601e2d637871",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":85,
              "y":526},
            "size":{
              "width":42,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"476e5f41a6cb4263b7525a13805ba843",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":85,
                  "y":526},
                "size":{
                  "width":42,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u121.png"}},
{
          "id":"6a8ba89509694151beefbb59658d9451",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":137,
              "y":527},
            "size":{
              "width":187,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c53b255c31e54d6e93349bf892099793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":137,
                  "y":527},
                "size":{
                  "width":187,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康/u131.png"}},
{
          "id":"a1e1cd4d751b4edca88d36b412e0a12c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":259,
              "y":402},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07ffd6113f5445b38de9c6c1c82cad64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":259,
                  "y":402},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea9a5cf7b9534641a678b96c9cc0556f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":259,
              "y":498},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf13211678b04fed9fadc4fd926d56e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":259,
                  "y":498},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67176d2d31f5446d91bbcb42d1ee5446",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":478},
            "size":{
              "width":243,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康/u163_line.png"}},
{
          "id":"f873f32e7081452f8d3bbae3dd4cd97c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":310},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55a09bd95388440a9e3b5a1f4fa4fe1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":310},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}]},
{
          "id":"03730475de84486ebaf79bd88a96cb64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":144,
              "y":113},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14144d57f5724bea9b3a1fab754339ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":113},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4204d380573141d995c47c2d1efa8f69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":562,
              "y":113},
            "size":{
              "width":82,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"614eddc9a53a479f86479187e915a2d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":562,
                  "y":113},
                "size":{
                  "width":82,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27e4f0a7238c44feab522ebe6dc78bdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":96,
              "y":1184},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d953ed416ccf4194949ef901e6b87304",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":96,
                  "y":1184},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b86014714ebf41e98d48df29b22455f8",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":890},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19abfffe9476452da164deddb285f74f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":153,
                  "y":890},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "b3f6f8e60b764e79b1679b672e478159":{
      "scriptId":"u0"},
    "95bd633746db42f58987278ae4df64a7":{
      "scriptId":"u1"},
    "2842ec25b1c844eabf101744a574f262":{
      "scriptId":"u2"},
    "bfbc7c25d783460894f087e419af34a8":{
      "scriptId":"u3"},
    "e23846b667e04592ad5b21b0192dfc71":{
      "scriptId":"u4"},
    "62e4e067468a4778bf85fab5615eaf6d":{
      "scriptId":"u5"},
    "177afb56cba14203adaf69670225fd40":{
      "scriptId":"u6"},
    "b8bac0d6a8d64d4185d1f9fffd34b4dc":{
      "scriptId":"u7"},
    "abc574e363a641e5b94f92baa740c955":{
      "scriptId":"u8"},
    "49ab16a71f1547a4b7707ce0b330a419":{
      "scriptId":"u9"},
    "dfe2bd57c0f140c58df3c803958c7ce1":{
      "scriptId":"u10"},
    "bc6de84c2c2045a28488298f6e63d19f":{
      "scriptId":"u11"},
    "2d87ebd7f92048ca815dd14c7b890737":{
      "scriptId":"u12"},
    "f8e02fdf58fe4c0988d62a94dc4164ef":{
      "scriptId":"u13"},
    "cf71fd367fe3438aacc4c6ac20451db4":{
      "scriptId":"u14"},
    "50e9907d40194ce5a51bf1f2b993e44e":{
      "scriptId":"u15"},
    "4211ee0dcf7c474da883c3effb619b6c":{
      "scriptId":"u16"},
    "94163222b8e744d39b9b9291a51a87b0":{
      "scriptId":"u17"},
    "7cc2e55e7589489a8f41cd49a78a221d":{
      "scriptId":"u18"},
    "13af1cc02b0f46a9a45eb9f32a061146":{
      "scriptId":"u19"},
    "e7949fb6948d45efa9edecaa53d2e8c6":{
      "scriptId":"u20"},
    "5ddb728b488949dd977596dcb06b2294":{
      "scriptId":"u21"},
    "7ece5237ca794c9d916345fe807c1633":{
      "scriptId":"u22"},
    "91fc56de7909487ea4214a07af83fcae":{
      "scriptId":"u23"},
    "020d502c5a83405eb68cd6235396aea8":{
      "scriptId":"u24"},
    "0c7cb211c3cb409d96d739a9abd2bc86":{
      "scriptId":"u25"},
    "bf546ed1ccf14bfc9cd27ac3d8cd9b32":{
      "scriptId":"u26"},
    "f58fab2e04ec41fa895b318d37c44eb9":{
      "scriptId":"u27"},
    "7f70061f94a2462ca469e42817205de1":{
      "scriptId":"u28"},
    "a652096393e04137a9a102411cdaf887":{
      "scriptId":"u29"},
    "9f14d49e2aa941cda6ab49f5cb0bc609":{
      "scriptId":"u30"},
    "ac3efb2944ad4415b519cd9fadfc1655":{
      "scriptId":"u31"},
    "f85a2947136f4265852ba97493d9a8dc":{
      "scriptId":"u32"},
    "4903df8a638e4fa9be8208659f25fae1":{
      "scriptId":"u33"},
    "96624e2eb1f24abb999f417e737dfb9d":{
      "scriptId":"u34"},
    "fda475028c174476bd5fdec21e9616dd":{
      "scriptId":"u35"},
    "b61011b197ca4a88bb9124c72d7c3ef1":{
      "scriptId":"u36"},
    "5c95653aac3d4b2593221e8c11d0c72e":{
      "scriptId":"u37"},
    "53c0287777e34a398e80ebaf2f88ed37":{
      "scriptId":"u38"},
    "3091b8c9ce1044758495f1ffe5b38b41":{
      "scriptId":"u39"},
    "f65539e8d3794118a70bcd121030a80e":{
      "scriptId":"u40"},
    "734b117aac1a442d807f71d512a90622":{
      "scriptId":"u41"},
    "37f37a62a1b740c187e57e9689dc2e09":{
      "scriptId":"u42"},
    "4a957e4da73b484b948359d3eea68fc1":{
      "scriptId":"u43"},
    "be01a32cbf35414d965dbcf946ee7059":{
      "scriptId":"u44"},
    "8dddac3a414d483997145efac8de75b1":{
      "scriptId":"u45"},
    "9c75af4c81f842eea1bb5c3f1eae33e0":{
      "scriptId":"u46"},
    "7e1d821f0b5644e68baaa687d7ed9a9e":{
      "scriptId":"u47"},
    "f5b27f6e41af471a9410902138bfd0df":{
      "scriptId":"u48"},
    "bc4c8479483c47789da66249227b08d3":{
      "scriptId":"u49"},
    "cc15252882124e3c8bb11344eb063847":{
      "scriptId":"u50"},
    "bf91bebfa31f4d358a5cf3a67a9cfd57":{
      "scriptId":"u51"},
    "ad2cb9deded74a5fa4f423b5315cf949":{
      "scriptId":"u52"},
    "e6f7d5bce6a745b0a235146a4eccce78":{
      "scriptId":"u53"},
    "b520212bb3e44bd49a64c809e30a7fa7":{
      "scriptId":"u54"},
    "5d096c06e05245d399e9b15b0d646028":{
      "scriptId":"u55"},
    "eaa4a6f9ee0c44f6b5cdbb38083faa64":{
      "scriptId":"u56"},
    "95a17fab1c394972846d4535be8aa24c":{
      "scriptId":"u57"},
    "9be8fab4bb194c089c8e22c645476612":{
      "scriptId":"u58"},
    "51598581f75a40e496fe4f542696ec7e":{
      "scriptId":"u59"},
    "48f9d7dc47d5403a89d3da2d9dfbf11a":{
      "scriptId":"u60"},
    "39f865bd925e48a79cb885b1abd57f87":{
      "scriptId":"u61"},
    "d9fed3b28e8843209a5e5813fd73e302":{
      "scriptId":"u62"},
    "298b8d54d2db4a558874e8a1fb9f75f0":{
      "scriptId":"u63"},
    "7af72fe55ad4437daead00d3a3602fd9":{
      "scriptId":"u64"},
    "1928c00e945f4fcea83474e58d63d26e":{
      "scriptId":"u65"},
    "f834da9c40a541b2b5e53500279a5e5d":{
      "scriptId":"u66"},
    "c5eadd2f71334353bbfc48b1380a1855":{
      "scriptId":"u67"},
    "baf1e3b3a8494302890a1a000a653411":{
      "scriptId":"u68"},
    "6247e77b871f460d85d7a33ea73aa33d":{
      "scriptId":"u69"},
    "aed5a89709f84384ba7d391d7c70b3f8":{
      "scriptId":"u70"},
    "37076794d7bf4164bb19eab4f088e917":{
      "scriptId":"u71"},
    "c705d07e5755409fa72f24a79d0d5cd7":{
      "scriptId":"u72"},
    "b28082b72fe243628deca642c3a0ba14":{
      "scriptId":"u73"},
    "b2529d532f6041df977340785006fed0":{
      "scriptId":"u74"},
    "f64d0dafc9ec42a49c48e42177ae5991":{
      "scriptId":"u75"},
    "418187e58b4b497c8263ea64ef4826f2":{
      "scriptId":"u76"},
    "eaba985d21654fe8b9e24c179760f30f":{
      "scriptId":"u77"},
    "6bc2f7ca3c954d51974bb17197f39c3d":{
      "scriptId":"u78"},
    "98ae8099152c46d9a19778f2d7888c43":{
      "scriptId":"u79"},
    "8fd77fa3d22341e69b8fa5d045e7c5cf":{
      "scriptId":"u80"},
    "7c4d6e4c2d9e45889cb670a7d85dded9":{
      "scriptId":"u81"},
    "236e178c430041a7a1bb6ca7034a0d18":{
      "scriptId":"u82"},
    "b561271025014d0d916f1d594aa39a41":{
      "scriptId":"u83"},
    "8f9905c85a244f6686cfad6ed79759f8":{
      "scriptId":"u84"},
    "f9883f0ebc4b47f1b65e3d630a50f856":{
      "scriptId":"u85"},
    "c0a14a202c124a8bb1050d59158979fa":{
      "scriptId":"u86"},
    "669231eab769442bb5dd7eec8f95946c":{
      "scriptId":"u87"},
    "de5323b08c2145d6bdd771a57c718c89":{
      "scriptId":"u88"},
    "b4771af9669744f384dad512dba8e234":{
      "scriptId":"u89"},
    "8c433536e2b34277a3366dc62d6a0c12":{
      "scriptId":"u90"},
    "9f78558026d1432fb7d3222b39e21037":{
      "scriptId":"u91"},
    "2c08b34c3e4e44feaabf601e2d637871":{
      "scriptId":"u92"},
    "476e5f41a6cb4263b7525a13805ba843":{
      "scriptId":"u93"},
    "6a8ba89509694151beefbb59658d9451":{
      "scriptId":"u94"},
    "c53b255c31e54d6e93349bf892099793":{
      "scriptId":"u95"},
    "a1e1cd4d751b4edca88d36b412e0a12c":{
      "scriptId":"u96"},
    "07ffd6113f5445b38de9c6c1c82cad64":{
      "scriptId":"u97"},
    "ea9a5cf7b9534641a678b96c9cc0556f":{
      "scriptId":"u98"},
    "cf13211678b04fed9fadc4fd926d56e7":{
      "scriptId":"u99"},
    "67176d2d31f5446d91bbcb42d1ee5446":{
      "scriptId":"u100"},
    "f873f32e7081452f8d3bbae3dd4cd97c":{
      "scriptId":"u101"},
    "55a09bd95388440a9e3b5a1f4fa4fe1b":{
      "scriptId":"u102"},
    "03730475de84486ebaf79bd88a96cb64":{
      "scriptId":"u103"},
    "14144d57f5724bea9b3a1fab754339ca":{
      "scriptId":"u104"},
    "4204d380573141d995c47c2d1efa8f69":{
      "scriptId":"u105"},
    "614eddc9a53a479f86479187e915a2d0":{
      "scriptId":"u106"},
    "27e4f0a7238c44feab522ebe6dc78bdf":{
      "scriptId":"u107"},
    "d953ed416ccf4194949ef901e6b87304":{
      "scriptId":"u108"},
    "b86014714ebf41e98d48df29b22455f8":{
      "scriptId":"u109"},
    "19abfffe9476452da164deddb285f74f":{
      "scriptId":"u110"}}});