$axure.loadCurrentPage({
  "url":"综述.html",
  "generationDate":new Date(1482837293820.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8d52d2a8716e4fcc983a884246298c19",
    "type":"Axure:Page",
    "name":"综述",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9f24763939a048078978a70172061b57",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":50},
            "size":{
              "width":222,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be6024647f9434b84acb14d5d520deb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":50},
                "size":{
                  "width":222,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cbcf96bf8e74e75b1345589f3203334",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":130},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cef2240f20248efae6ac5fb89925e83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":130},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2c57958b6754c44b3efa28ce56733de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":207,
              "y":132},
            "size":{
              "width":441,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a2d4cad989d4ad4a1aaff1e722cd80c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":207,
                  "y":132},
                "size":{
                  "width":441,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62c6fa14c78c4c64b7291456e8f265c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":198},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"293dff52a4ee4ecc8d08a30723609977",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":198},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4bec71f361a4579a6cc82aa21ac68c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":207,
              "y":198},
            "size":{
              "width":341,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24c48bd58a1845669c69db5a8711b388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":207,
                  "y":198},
                "size":{
                  "width":341,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21845d34661f42b2aa7990cac7bfecfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":266},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bfe619b0b054db4963008022ac6971d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":266},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d05c9ef3069415f9b352cd7208630e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":207,
              "y":266},
            "size":{
              "width":621,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bded887515b46c3b311ca000973ce48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":207,
                  "y":266},
                "size":{
                  "width":621,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3f1d7841e9441428a233ea54030a16b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":334},
            "size":{
              "width":51,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b51455714fe049dcb0690da442fdbe74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":334},
                "size":{
                  "width":51,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c5ae936182642979c0374a1231316c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":207,
              "y":334},
            "size":{
              "width":332,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e01264215554bd984f37b429f90e3cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":207,
                  "y":334},
                "size":{
                  "width":332,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6b703316bfd41849372839abccfc332",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":427},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b36209438e864b0e89fb1114971dcde8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":427},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63eaa364db3d4bde8b449ad8e3b16b7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":207,
              "y":427},
            "size":{
              "width":457,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b65e15d96984473baa977204d380415f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":207,
                  "y":427},
                "size":{
                  "width":457,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67428953bc164a8fb7e182f15748821e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":384},
            "size":{
              "width":810,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/综述/u22_line.png"}},
{
          "id":"1e5369ff93d643b396fa88fe31b57c6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":502},
            "size":{
              "width":360,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ce242d643b942fdb9085ab18a0d35bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":207,
                  "y":502},
                "size":{
                  "width":360,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69a26f0947aa438d9c580b5183828c62",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":60,
              "y":502},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43d79e1b577a4305b0cfc7e6f922016d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":502},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19ba758834704be0aafb9aaa3b2cded3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":520},
            "size":{
              "width":473,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c058b55e9e3f41ae87c0dddca018e3f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":207,
                  "y":520},
                "size":{
                  "width":473,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9f24763939a048078978a70172061b57":{
      "scriptId":"u0"},
    "4be6024647f9434b84acb14d5d520deb":{
      "scriptId":"u1"},
    "0cbcf96bf8e74e75b1345589f3203334":{
      "scriptId":"u2"},
    "4cef2240f20248efae6ac5fb89925e83":{
      "scriptId":"u3"},
    "d2c57958b6754c44b3efa28ce56733de":{
      "scriptId":"u4"},
    "5a2d4cad989d4ad4a1aaff1e722cd80c":{
      "scriptId":"u5"},
    "62c6fa14c78c4c64b7291456e8f265c5":{
      "scriptId":"u6"},
    "293dff52a4ee4ecc8d08a30723609977":{
      "scriptId":"u7"},
    "b4bec71f361a4579a6cc82aa21ac68c3":{
      "scriptId":"u8"},
    "24c48bd58a1845669c69db5a8711b388":{
      "scriptId":"u9"},
    "21845d34661f42b2aa7990cac7bfecfc":{
      "scriptId":"u10"},
    "4bfe619b0b054db4963008022ac6971d":{
      "scriptId":"u11"},
    "9d05c9ef3069415f9b352cd7208630e5":{
      "scriptId":"u12"},
    "6bded887515b46c3b311ca000973ce48":{
      "scriptId":"u13"},
    "f3f1d7841e9441428a233ea54030a16b":{
      "scriptId":"u14"},
    "b51455714fe049dcb0690da442fdbe74":{
      "scriptId":"u15"},
    "0c5ae936182642979c0374a1231316c1":{
      "scriptId":"u16"},
    "2e01264215554bd984f37b429f90e3cc":{
      "scriptId":"u17"},
    "b6b703316bfd41849372839abccfc332":{
      "scriptId":"u18"},
    "b36209438e864b0e89fb1114971dcde8":{
      "scriptId":"u19"},
    "63eaa364db3d4bde8b449ad8e3b16b7e":{
      "scriptId":"u20"},
    "b65e15d96984473baa977204d380415f":{
      "scriptId":"u21"},
    "67428953bc164a8fb7e182f15748821e":{
      "scriptId":"u22"},
    "1e5369ff93d643b396fa88fe31b57c6a":{
      "scriptId":"u23"},
    "3ce242d643b942fdb9085ab18a0d35bd":{
      "scriptId":"u24"},
    "69a26f0947aa438d9c580b5183828c62":{
      "scriptId":"u25"},
    "43d79e1b577a4305b0cfc7e6f922016d":{
      "scriptId":"u26"},
    "19ba758834704be0aafb9aaa3b2cded3":{
      "scriptId":"u27"},
    "c058b55e9e3f41ae87c0dddca018e3f3":{
      "scriptId":"u28"}}});