$axure.loadCurrentPage({
  "url":"综述.html",
  "generationDate":new Date(1484017748413.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8d52d2a8716e4fcc983a884246298c19",
    "type":"Axure:Page",
    "name":"综述",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9f24763939a048078978a70172061b57",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":53},
            "size":{
              "width":222,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be6024647f9434b84acb14d5d520deb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":53},
                "size":{
                  "width":222,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cbcf96bf8e74e75b1345589f3203334",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":173},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cef2240f20248efae6ac5fb89925e83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":173},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2c57958b6754c44b3efa28ce56733de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":207,
              "y":175},
            "size":{
              "width":441,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a2d4cad989d4ad4a1aaff1e722cd80c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":207,
                  "y":175},
                "size":{
                  "width":441,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62c6fa14c78c4c64b7291456e8f265c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":257},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"293dff52a4ee4ecc8d08a30723609977",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":257},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4bec71f361a4579a6cc82aa21ac68c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":207,
              "y":257},
            "size":{
              "width":633,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24c48bd58a1845669c69db5a8711b388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":207,
                  "y":257},
                "size":{
                  "width":633,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21845d34661f42b2aa7990cac7bfecfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":340},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bfe619b0b054db4963008022ac6971d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":340},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d05c9ef3069415f9b352cd7208630e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":207,
              "y":340},
            "size":{
              "width":501,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bded887515b46c3b311ca000973ce48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":207,
                  "y":340},
                "size":{
                  "width":501,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6b703316bfd41849372839abccfc332",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":419},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b36209438e864b0e89fb1114971dcde8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":419},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63eaa364db3d4bde8b449ad8e3b16b7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":207,
              "y":419},
            "size":{
              "width":457,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b65e15d96984473baa977204d380415f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":207,
                  "y":419},
                "size":{
                  "width":457,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9f24763939a048078978a70172061b57":{
      "scriptId":"u0"},
    "4be6024647f9434b84acb14d5d520deb":{
      "scriptId":"u1"},
    "0cbcf96bf8e74e75b1345589f3203334":{
      "scriptId":"u2"},
    "4cef2240f20248efae6ac5fb89925e83":{
      "scriptId":"u3"},
    "d2c57958b6754c44b3efa28ce56733de":{
      "scriptId":"u4"},
    "5a2d4cad989d4ad4a1aaff1e722cd80c":{
      "scriptId":"u5"},
    "62c6fa14c78c4c64b7291456e8f265c5":{
      "scriptId":"u6"},
    "293dff52a4ee4ecc8d08a30723609977":{
      "scriptId":"u7"},
    "b4bec71f361a4579a6cc82aa21ac68c3":{
      "scriptId":"u8"},
    "24c48bd58a1845669c69db5a8711b388":{
      "scriptId":"u9"},
    "21845d34661f42b2aa7990cac7bfecfc":{
      "scriptId":"u10"},
    "4bfe619b0b054db4963008022ac6971d":{
      "scriptId":"u11"},
    "9d05c9ef3069415f9b352cd7208630e5":{
      "scriptId":"u12"},
    "6bded887515b46c3b311ca000973ce48":{
      "scriptId":"u13"},
    "b6b703316bfd41849372839abccfc332":{
      "scriptId":"u14"},
    "b36209438e864b0e89fb1114971dcde8":{
      "scriptId":"u15"},
    "63eaa364db3d4bde8b449ad8e3b16b7e":{
      "scriptId":"u16"},
    "b65e15d96984473baa977204d380415f":{
      "scriptId":"u17"}}});